//! Safe Python-to-NME conversion.
//!
//! Conversion is deliberately semantics-preserving: lines with a clear NME
//! equivalent are rewritten and every other valid Python line remains
//! advanced syntax. Because all three levels may coexist, the result is still
//! a complete NME program rather than a partial or lossy translation.

use std::collections::HashSet;

use rustpython_parser::{parse as parse_python, Mode, Tok};

use crate::diagnostics::{korean_particle, Diagnostic, DiagnosticCode, Span};
use crate::lexer::{self, LogicalLine, Token};
use crate::lower::{apply_edits, Edit};
use crate::render::{asks_for_a_length, Rewrite};

// Input actions may also appear after their target (`name ask ...`). An
// assignment target with one of these names would make `set prompt to ...`
// parse as an input command, so the lossless choice is to retain Python.
const AMBIGUOUS_TARGET_NAMES: &[&str] = &[
    "ask",
    "prompt",
    "question",
    "number",
    "numeric",
    "숫자",
    "숫자로",
    "수로",
    "물어봐",
    "물어봐줘",
    "물어보세요",
    "질문해",
    "질문해줘",
    "입력받아",
    "입력받아줘",
    "입력받아주세요",
    "물어봐요",
    "물어봐주세요",
    "질문해주세요",
];

// These names have a conversational meaning before the parser reaches the
// ordinary-Python-expression fallback. Converting an expression containing
// one (or one recoverable typo of one) could silently select that NME meaning.
const RESERVED_EXPRESSION_NAMES: &[&str] = &[
    // NME literal aliases.
    "true",
    "false",
    "none",
    "null",
    "참",
    "거짓",
    "없음",
    // Random-value sentence syntax.
    "random",
    "randomnumber",
    "랜덤",
    "랜덤정수",
    "무작위",
    "무작위숫자",
    "randomchoice",
    "pick",
    "랜덤선택",
    "하나골라",
    "골라",
    // Repeat markers can be mistaken for the marker generated by conversion.
    "times",
    "번",
    // Condition connectors, predicates, and leading filler words.
    "then",
    "exists",
    "present",
    "missing",
    "absent",
    "greater",
    "above",
    "less",
    "below",
    "equals",
    "equal",
    "그러면",
    "그럼",
    "경우",
    "때",
    "일때",
    "있으면",
    "있다면",
    "없으면",
    "없다면",
    "같으면",
    "같다면",
    "이면",
    "라면",
    "크면",
    "크다면",
    "작으면",
    "작다면",
    "please",
    "really",
    "the",
    "정말",
    "혹시",
];

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SyntaxLevel {
    Advanced,
    Beginner,
    Sentence,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Language {
    English,
    Korean,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Conversion {
    pub source: String,
    pub changed_lines: usize,
}

/// Convert valid Python into the requested NME surface level.
///
/// Unsupported constructs remain byte-identical advanced Python. This is the
/// only lossless behavior possible because advanced Python is itself one of
/// NME's three syntax levels.
pub fn convert_python(
    source: &str,
    level: SyntaxLevel,
    language: Language,
) -> Result<Conversion, Vec<Diagnostic>> {
    if let Err(error) = parse_python(source, Mode::Module, "<python>") {
        let start = usize::from(error.offset).min(source.len().saturating_sub(1));
        return Err(vec![Diagnostic::bilingual(
            DiagnosticCode::ConvertInvalidPython,
            format!("the Python source is not valid: {}", error.error),
            format!("올바른 Python 코드가 아닙니다: {}", error.error),
            Span::new(start, (start + 1).min(source.len())),
        )
        .with_bilingual_hint(
            "fix this Python error before converting it to NME",
            "NME로 변환하기 전에 Python 문법을 먼저 고쳐 주세요",
        )]);
    }

    if level == SyntaxLevel::Advanced {
        return Ok(Conversion {
            source: source.to_string(),
            changed_lines: 0,
        });
    }

    let lines = lexer::logical_lines(source).map_err(|problem| vec![problem])?;
    let containers = container_names(source);
    let mut edits = Vec::new();
    // Reading and writing a file is the one rewrite that is *meant* to change
    // the Python: `open(p).read()` becomes `Path(p).read_text()`, which is the
    // shape NME writes. So those edits are made first and the file they leave
    // is what everything else is checked against.
    let mut file_lines = Vec::new();
    for line in &lines {
        // Replacing a logical statement that covers more than one physical
        // line would collapse source lines. The byte check is only about edit
        // geometry; all Python structure below is still decided from tokens.
        if spans_multiple_physical_lines(source, line) {
            continue;
        }
        if let Some(replacement) = convert_file_io(source, &line.tokens, level, language) {
            file_lines.push(Edit {
                span: line.span,
                replacement,
            });
            continue;
        }
        let spellings = convert_line(source, line, level, language, &containers);
        if !spellings.is_empty() {
            edits.push(spellings);
        }
    }
    let with_files = apply_edits(source, &file_lines);
    let (file_lines, reference) = match crate::transpile::transpile(&with_files) {
        Ok(python) => (file_lines, python),
        Err(_) => (Vec::new(), source.to_string()),
    };
    // Every reading is proved by lowering it again, so no one line can drift.
    // What that check cannot see is the rest of the file: a message written as
    // words may hold a name the program binds later, and the sentence would
    // then print its value rather than the word. So the whole file is asked
    // once, and what does not hold is put back.
    let edits = edits_that_hold(source, &reference, &file_lines, &edits);
    let changed_lines = edits.len();
    Ok(Conversion {
        source: apply_edits(source, &edits),
        changed_lines,
    })
}

/// The edits that leave the program saying exactly what it said.
///
/// The edits are added back in groups rather than one at a time: on a long
/// file with a handful of lines that cannot be written at this level, one
/// transpile per line meant a person waiting. Halving a group asks the same
/// question of far fewer programs and keeps the same answer.
fn edits_that_hold(
    source: &str,
    python: &str,
    already: &[Edit],
    lines: &[Vec<Edit>],
) -> Vec<Edit> {
    let mut kept = already.to_vec();
    keep_what_holds(source, python, &mut kept, lines);
    kept
}

fn keep_what_holds(source: &str, python: &str, kept: &mut Vec<Edit>, lines: &[Vec<Edit>]) {
    if lines.is_empty() {
        return;
    }
    let before = kept.len();
    kept.extend(lines.iter().filter_map(|line| line.first().cloned()));
    if transpiles_the_same(&apply_edits(source, kept), python) {
        return;
    }
    kept.truncate(before);
    if let [spellings] = lines {
        // One line on its own, and its best spelling did not hold. The others
        // are plainer rather than different: `show "Hello"` says what `show
        // Hello` says without reading the message as words.
        for spelling in spellings.iter().skip(1) {
            kept.push(spelling.clone());
            if transpiles_the_same(&apply_edits(source, kept), python) {
                return;
            }
            kept.pop();
        }
        return;
    }
    let middle = lines.len() / 2;
    keep_what_holds(source, python, kept, &lines[..middle]);
    keep_what_holds(source, python, kept, &lines[middle..]);
}

fn transpiles_the_same(candidate: &str, python: &str) -> bool {
    crate::transpile::transpile(candidate)
        .is_ok_and(|produced| crate::transpile::is_the_same_program(&produced, python))
}

pub(crate) fn convert_line(
    source: &str,
    line: &LogicalLine,
    level: SyntaxLevel,
    language: Language,
    containers: &HashSet<String>,
) -> Vec<Edit> {
    // Best spelling first. Which of them a file can actually take is settled
    // by transpiling the whole thing, because a message written as words may
    // hold a name the program makes later on.
    let mut spellings = vec![
        convert_by_reading_it_back(source, line, level, language, containers, true),
        convert_by_reading_it_back(source, line, level, language, containers, false),
        convert_print(source, &line.tokens, level, language)
            .or_else(|| convert_input(source, &line.tokens, level, language))
            .or_else(|| convert_range_loop(source, &line.tokens, level, language))
            .or_else(|| convert_condition(source, &line.tokens, level, language))
            .or_else(|| convert_assignment(source, &line.tokens, level, language)),
    ]
    .into_iter()
    .flatten()
    .collect::<Vec<_>>();
    spellings.dedup();
    spellings
        .into_iter()
        .map(|replacement| Edit {
            span: line.span,
            replacement,
        })
        .collect()
}

/// The line read back into the statement that would have written it, and then
/// written again in the level and language asked for.
///
/// This is the general way in, and it is the one that keeps the two halves of
/// the tidier in step: the words come from [`crate::render`], the same place
/// the words for a line that was already NME come from, so a program that
/// arrives as Python lands in exactly the spelling a program that arrived as
/// sentences lands in. [`crate::from_python`] proves its reading by lowering
/// it again, so nothing here can change what the line does.
/// The names a Python file fills with things rather than with one value.
///
/// `len(x)` is one piece of Python and two sentences — `how many friends`
/// counts things, `the length of name` counts letters — and the only way to
/// tell them apart is what the program put in the name. A file that was
/// already NME gets this from the parser; a file of Python is read here.
pub(crate) fn container_names(source: &str) -> HashSet<String> {
    let mut names = HashSet::new();
    for line in source.lines() {
        let line = line.trim();
        if let Some((target, value)) = line.split_once(" = ") {
            let value = value.trim();
            if (value.starts_with('[') && value.ends_with(']'))
                || (value.starts_with('{') && value.ends_with('}'))
                || value.ends_with(".splitlines()")
                || value.contains(".split(")
            {
                names.insert(target.trim().to_string());
            }
        }
        for method in [".append(", ".remove(", ".sort()", ".reverse()"] {
            if let Some((target, _)) = line.split_once(method) {
                names.insert(target.trim().to_string());
            }
        }
        // `prices["Mina"] = 90` fills a record.
        if let Some((target, _)) = line.split_once('[') {
            if line.contains("] = ") {
                names.insert(target.trim().to_string());
            }
        }
    }
    names.retain(|name| {
        !name.is_empty()
            && !name.starts_with(|character: char| character.is_ascii_digit())
            && name
                .chars()
                .all(|character| character.is_alphanumeric() || character == '_')
    });
    names
}

fn convert_by_reading_it_back(
    source: &str,
    line: &LogicalLine,
    level: SyntaxLevel,
    language: Language,
    containers: &HashSet<String>,
    read_messages: bool,
) -> Option<String> {
    let written = line.text(source);
    let stmt = crate::from_python::statement_from_python(written)?;
    Rewrite {
        source,
        level,
        language,
        length_not_count: asks_for_a_length(written),
        colon: written.trim_end().ends_with(':'),
        containers,
        read_messages,
    }
    .statement(&stmt, written)
}

/// Sentence-level file conversions. `x = open("f").read()` becomes
/// `read "f" into x`; `open("f", "w").write(v)` becomes `write v to "f"`,
/// with Korean spellings for Korean output. `pathlib.Path(...).read_text()`
/// / `.write_text(...)` convert the same way. Only the sentence level has
/// these natural forms, so beginner conversion keeps the Python unchanged.
fn convert_file_io(
    source: &str,
    tokens: &[Token],
    level: SyntaxLevel,
    language: Language,
) -> Option<String> {
    if level != SyntaxLevel::Sentence {
        return None;
    }
    if let Some((target, path)) = read_assignment(source, tokens) {
        if is_ambiguous_target(target) {
            return None;
        }
        let path_text = text_of(source, std::slice::from_ref(path));
        return Some(match language {
            Language::English => format!("read {path_text} into {target}"),
            Language::Korean => format!("{target}에 {path_text} 읽어서"),
        });
    }
    if let Some((path, value)) = write_statement(source, tokens) {
        if !is_safe_scalar_expression(value) {
            return None;
        }
        let path_text = text_of(source, std::slice::from_ref(path));
        let value_text = sentence_value(source, value);
        return Some(match language {
            Language::English => format!("write {value_text} to {path_text}"),
            Language::Korean => format!("{path_text} 파일에 {value_text}를 저장해"),
        });
    }
    None
}

/// `x = open("f").read()` / `x = Path("f").read_text()`.
fn read_assignment<'a>(source: &str, tokens: &'a [Token]) -> Option<(&'a str, &'a Token)> {
    if tokens.len() < 10 || !matches!(tokens[1].tok, Tok::Equal) {
        return None;
    }
    let target = match &tokens[0].tok {
        Tok::Name { name } => name.as_str(),
        _ => return None,
    };
    let (path, method) = call_shape(source, &tokens[2..])?;
    if method != "read" && method != "read_text" {
        return None;
    }
    Some((target, path))
}

/// Detects `open(path)` / `open(path, "r")` / `Path(path)` followed by
/// `.method()` with empty arguments.
fn call_shape<'a>(source: &str, tokens: &'a [Token]) -> Option<(&'a Token, &'a str)> {
    let dot_at = tokens
        .iter()
        .position(|token| matches!(token.tok, Tok::Dot))?;
    let base = &tokens[..dot_at];
    if base.len() < 4
        || !matches!(base[0].tok, Tok::Name { .. })
        || !matches!(base[1].tok, Tok::Lpar)
        || !matches!(base[base.len() - 1].tok, Tok::Rpar)
    {
        return None;
    }
    let base_name = match &base[0].tok {
        Tok::Name { name } => name.as_str(),
        _ => return None,
    };
    if base_name != "open" && base_name != "Path" {
        return None;
    }
    let path = match base.get(2) {
        Some(token) if matches!(token.tok, Tok::String { .. }) => token,
        _ => return None,
    };
    if base.len() > 4 {
        // `open(path, mode)`: only accept an explicit read mode `"r"`.
        if base.len() != 6
            || !matches!(base[3].tok, Tok::Comma)
            || text_of(source, std::slice::from_ref(&base[4])) != "\"r\""
        {
            return None;
        }
    }
    let method_tokens = &tokens[dot_at + 1..];
    if method_tokens.len() != 3
        || !matches!(method_tokens[0].tok, Tok::Name { .. })
        || !matches!(method_tokens[1].tok, Tok::Lpar)
        || !matches!(method_tokens[2].tok, Tok::Rpar)
    {
        return None;
    }
    let method = match &method_tokens[0].tok {
        Tok::Name { name } => name.as_str(),
        _ => return None,
    };
    Some((path, method))
}

/// `open("f", "w").write(value)` / `Path("f").write_text(value)`.
fn write_statement<'a>(source: &str, tokens: &'a [Token]) -> Option<(&'a Token, &'a [Token])> {
    let dot_at = tokens
        .iter()
        .position(|token| matches!(token.tok, Tok::Dot))?;
    let base = &tokens[..dot_at];
    if base.len() < 4
        || !matches!(base[0].tok, Tok::Name { .. })
        || !matches!(base[1].tok, Tok::Lpar)
        || !matches!(base[base.len() - 1].tok, Tok::Rpar)
    {
        return None;
    }
    let base_name = match &base[0].tok {
        Tok::Name { name } => name.as_str(),
        _ => return None,
    };
    let path = match base.get(2) {
        Some(token) if matches!(token.tok, Tok::String { .. }) => token,
        _ => return None,
    };
    let method_tokens = &tokens[dot_at + 1..];
    if method_tokens.len() < 4
        || !matches!(method_tokens[0].tok, Tok::Name { .. })
        || !matches!(method_tokens[1].tok, Tok::Lpar)
        || !matches!(method_tokens[method_tokens.len() - 1].tok, Tok::Rpar)
    {
        return None;
    }
    let method = match &method_tokens[0].tok {
        Tok::Name { name } => name.as_str(),
        _ => return None,
    };
    let value = &method_tokens[2..method_tokens.len() - 1];
    if value.is_empty() {
        return None;
    }
    match (base_name, method, base.len()) {
        ("open", "write", 6)
            if matches!(base[3].tok, Tok::Comma)
                && text_of(source, std::slice::from_ref(&base[4])) == "\"w\"" =>
        {
            Some((path, value))
        }
        ("Path", "write_text", 4) => Some((path, value)),
        _ => None,
    }
}

fn convert_print(
    source: &str,
    tokens: &[Token],
    level: SyntaxLevel,
    language: Language,
) -> Option<String> {
    let argument = exact_call_arguments(tokens, "print")?;
    if !is_safe_scalar_expression(argument) {
        return None;
    }
    // A lone name is prose-sensitive and requires scope knowledge identical
    // to the NME parser. Retaining Python avoids both scope leaks and aliases
    // such as `true` being reinterpreted as an NME literal.
    if matches!(
        argument,
        [Token {
            tok: Tok::Name { .. },
            ..
        }]
    ) {
        return None;
    }
    let value = sentence_value(source, argument);
    // A single piece of text is a whole value, and Korean stands its verb
    // after one: `"안녕하세요" 말해줘`. `보여줘 "안녕하세요"` put a converted line
    // in English word order while every hand-written line around it read the
    // other way. Anything with an operator in it keeps the verb in front.
    let one_piece_of_text = matches!(
        argument,
        [Token {
            tok: Tok::String { .. },
            ..
        }]
    );
    Some(match (level, language) {
        (SyntaxLevel::Beginner, Language::English) => format!("say {value}"),
        (SyntaxLevel::Beginner, Language::Korean) => format!("말해 {value}"),
        (SyntaxLevel::Sentence, Language::English) => format!("show {value}"),
        (SyntaxLevel::Sentence, Language::Korean) if one_piece_of_text => {
            format!("{value} 말해줘")
        }
        (SyntaxLevel::Sentence, Language::Korean) => format!("보여줘 {value}"),
        (SyntaxLevel::Advanced, _) => return None,
    })
}

fn convert_input(
    source: &str,
    tokens: &[Token],
    level: SyntaxLevel,
    language: Language,
) -> Option<String> {
    let (target, kind, prompt_tokens) = input_assignment(tokens)?;
    if is_ambiguous_target(target) {
        return None;
    }
    if !prompt_tokens.is_empty() && !is_safe_scalar_expression(prompt_tokens) {
        return None;
    }
    let prompt = if prompt_tokens.is_empty() {
        None
    } else {
        // Sentence prompts beginning with a name are prose, while precise
        // beginner prompts would require duplicating parser scope knowledge.
        // Keep both cases as Python rather than risk changing a name lookup.
        if matches!(
            prompt_tokens.first().map(|token| &token.tok),
            Some(Tok::Name { .. })
        ) {
            return None;
        }
        Some(sentence_value(source, prompt_tokens))
    };
    let prompt_with_beginner_comma = prompt.as_ref().map(|value| format!(", {value}"));
    let prompt_with_space = prompt.as_ref().map(|value| format!(" {value}"));

    Some(match (level, language, kind) {
        (SyntaxLevel::Beginner, Language::English, InputFlavor::Text) => {
            format!(
                "ask {target}{}",
                prompt_with_beginner_comma.unwrap_or_default()
            )
        }
        (SyntaxLevel::Beginner, Language::Korean, InputFlavor::Text) => {
            format!(
                "물어봐 {target}{}",
                prompt_with_beginner_comma.unwrap_or_default()
            )
        }
        (SyntaxLevel::Sentence, Language::English, InputFlavor::Text) => {
            format!("ask {target}{}", prompt_with_space.unwrap_or_default())
        }
        (SyntaxLevel::Sentence, Language::English, InputFlavor::Number) => {
            format!(
                "ask number {target}{}",
                prompt_with_space.unwrap_or_default()
            )
        }
        (SyntaxLevel::Sentence, Language::Korean, InputFlavor::Text) => {
            format!(
                "{target}{} 물어봐{}",
                korean_particle(target, "을", "를"),
                prompt_with_space.unwrap_or_default()
            )
        }
        (SyntaxLevel::Sentence, Language::Korean, InputFlavor::Number) => {
            format!(
                "{target}{} 숫자로 물어봐{}",
                korean_particle(target, "을", "를"),
                prompt_with_space.unwrap_or_default()
            )
        }
        // Numeric input is a sentence feature; beginner conversion keeps this
        // advanced Python line rather than changing its semantics.
        (SyntaxLevel::Beginner, _, InputFlavor::Number) | (SyntaxLevel::Advanced, _, _) => {
            return None;
        }
    })
}

#[derive(Clone, Copy)]
enum InputFlavor {
    Text,
    Number,
}

fn input_assignment(tokens: &[Token]) -> Option<(&str, InputFlavor, &[Token])> {
    let [Token {
        tok: Tok::Name { name: target },
        ..
    }, Token {
        tok: Tok::Equal, ..
    }, rest @ ..] = tokens
    else {
        return None;
    };
    if let Some(arguments) = exact_call_arguments(rest, "input") {
        return Some((target, InputFlavor::Text, arguments));
    }
    let int_arguments = exact_call_arguments(rest, "int")?;
    if let Some(arguments) = exact_call_arguments(int_arguments, "input") {
        return Some((target, InputFlavor::Number, arguments));
    }
    None
}

fn exact_call_arguments<'a>(tokens: &'a [Token], name: &str) -> Option<&'a [Token]> {
    if tokens.len() < 3
        || !name_is(&tokens[0], name)
        || !matches!(tokens[1].tok, Tok::Lpar)
        || !matches!(tokens[tokens.len() - 1].tok, Tok::Rpar)
    {
        return None;
    }

    let mut depth = 0usize;
    for (index, token) in tokens.iter().enumerate().skip(1) {
        match token.tok {
            Tok::Lpar => depth += 1,
            Tok::Rpar => {
                depth = depth.checked_sub(1)?;
                if depth == 0 && index != tokens.len() - 1 {
                    return None;
                }
            }
            _ => {}
        }
    }
    (depth == 0).then_some(&tokens[2..tokens.len() - 1])
}

fn convert_range_loop(
    source: &str,
    tokens: &[Token],
    level: SyntaxLevel,
    language: Language,
) -> Option<String> {
    if tokens.len() < 8
        || !matches!(tokens[0].tok, Tok::For)
        || !name_is(&tokens[1], "_")
        || !matches!(tokens[2].tok, Tok::In)
        || !name_is(&tokens[3], "range")
        || !matches!(tokens[4].tok, Tok::Lpar)
        || !matches!(tokens[tokens.len() - 2].tok, Tok::Rpar)
        || !matches!(tokens[tokens.len() - 1].tok, Tok::Colon)
    {
        return None;
    }
    let count_tokens = &tokens[5..tokens.len() - 2];
    if !is_safe_scalar_expression(count_tokens) {
        return None;
    }
    let count = text_of(source, count_tokens);
    Some(match (level, language) {
        (SyntaxLevel::Beginner, Language::English) => format!("{count} times:"),
        (SyntaxLevel::Beginner, Language::Korean) => format!("{count} 번:"),
        (SyntaxLevel::Sentence, Language::English) => format!("repeat {count} times"),
        (SyntaxLevel::Sentence, Language::Korean) => format!("{count} 번 반복해"),
        (SyntaxLevel::Advanced, _) => return None,
    })
}

fn convert_condition(
    source: &str,
    tokens: &[Token],
    level: SyntaxLevel,
    language: Language,
) -> Option<String> {
    if tokens.len() < 3
        || !matches!(tokens[0].tok, Tok::If)
        || !matches!(tokens[tokens.len() - 1].tok, Tok::Colon)
    {
        return None;
    }
    let condition_tokens = &tokens[1..tokens.len() - 1];
    if !is_safe_scalar_expression(condition_tokens) {
        return None;
    }
    if matches!(
        condition_tokens,
        [Token {
            tok: Tok::Name { .. },
            ..
        }]
    ) {
        return None;
    }
    let condition = text_of(source, condition_tokens);
    Some(match (level, language) {
        (SyntaxLevel::Beginner, Language::English) => format!("when {condition}:"),
        (SyntaxLevel::Beginner, Language::Korean) => format!("만약 {condition}:"),
        (SyntaxLevel::Sentence, Language::English) => format!("if {condition}"),
        (SyntaxLevel::Sentence, Language::Korean) => format!("만약에 {condition}"),
        (SyntaxLevel::Advanced, _) => return None,
    })
}

fn convert_assignment(
    source: &str,
    tokens: &[Token],
    level: SyntaxLevel,
    language: Language,
) -> Option<String> {
    if level != SyntaxLevel::Sentence {
        return None;
    }
    let [Token {
        tok: Tok::Name { name: target },
        ..
    }, Token {
        tok: Tok::Equal, ..
    }, value @ ..] = tokens
    else {
        return None;
    };
    if is_ambiguous_target(target) {
        return None;
    }
    if !is_safe_scalar_expression(value) {
        return None;
    }
    // A lone name is prose-sensitive in sentence syntax. Assignment discovery
    // can be reordered by conversion, so keep every bare-name copy as Python.
    if matches!(
        value,
        [Token {
            tok: Tok::Name { .. },
            ..
        }]
    ) {
        return None;
    }
    let value = sentence_value(source, value);
    Some(match language {
        Language::English => format!("set {target} to {value}"),
        Language::Korean => format!("{target}{} {value}", korean_particle(target, "은", "는")),
    })
}

fn sentence_value(source: &str, tokens: &[Token]) -> String {
    text_of(source, tokens).to_string()
}

fn is_safe_scalar_expression(tokens: &[Token]) -> bool {
    let mut needs_operand = true;
    for token in tokens {
        if needs_operand {
            match token.tok {
                Tok::Plus | Tok::Minus => {}
                Tok::Name { ref name } if !conflicts_with_sentence_syntax(name) => {
                    needs_operand = false;
                }
                Tok::Int { .. }
                | Tok::Float { .. }
                | Tok::Complex { .. }
                | Tok::String { .. }
                | Tok::False
                | Tok::None
                | Tok::True => needs_operand = false,
                _ => return false,
            }
        } else {
            match token.tok {
                Tok::Plus
                | Tok::Minus
                | Tok::Star
                | Tok::DoubleStar
                | Tok::Slash
                | Tok::DoubleSlash
                | Tok::Percent
                | Tok::EqEqual
                | Tok::NotEqual
                | Tok::Less
                | Tok::Greater
                | Tok::LessEqual
                | Tok::GreaterEqual => needs_operand = true,
                _ => return false,
            }
        }
    }
    !tokens.is_empty() && !needs_operand
}

pub(crate) fn spans_multiple_physical_lines(source: &str, line: &LogicalLine) -> bool {
    if source[line.span.start..line.span.end]
        .bytes()
        .any(|byte| matches!(byte, b'\n' | b'\r'))
    {
        return true;
    }

    // An explicit continuation may occur after the last significant token,
    // outside LogicalLine::span. Inspect only that physical-line tail; this
    // is edit geometry, not Python structure. A backslash in a comment may
    // conservatively skip a safe conversion, which is still lossless.
    source[line.span.end..]
        .bytes()
        .take_while(|byte| !matches!(byte, b'\n' | b'\r'))
        .any(|byte| byte == b'\\')
}

fn is_ambiguous_target(name: &str) -> bool {
    AMBIGUOUS_TARGET_NAMES
        .iter()
        .any(|reserved| name.eq_ignore_ascii_case(reserved))
}

fn conflicts_with_sentence_syntax(name: &str) -> bool {
    RESERVED_EXPRESSION_NAMES
        .iter()
        .any(|reserved| recovered_word_match(name, reserved))
}

fn recovered_word_match(actual: &str, expected: &str) -> bool {
    if actual.eq_ignore_ascii_case(expected) {
        return true;
    }
    if actual.chars().count() < 2 {
        return false;
    }
    let actual = actual
        .chars()
        .flat_map(char::to_lowercase)
        .collect::<Vec<_>>();
    let expected = expected
        .chars()
        .flat_map(char::to_lowercase)
        .collect::<Vec<_>>();
    if actual.len().abs_diff(expected.len()) > 1 {
        return false;
    }
    if actual.len() == expected.len() {
        let differences = actual
            .iter()
            .zip(&expected)
            .enumerate()
            .filter_map(|(index, (left, right))| (left != right).then_some(index))
            .collect::<Vec<_>>();
        return differences.len() == 1
            || (differences.len() == 2
                && differences[1] == differences[0] + 1
                && actual[differences[0]] == expected[differences[1]]
                && actual[differences[1]] == expected[differences[0]]);
    }
    let (shorter, longer) = if actual.len() < expected.len() {
        (&actual, &expected)
    } else {
        (&expected, &actual)
    };
    let (mut short_at, mut long_at, mut skipped) = (0, 0, false);
    while short_at < shorter.len() && long_at < longer.len() {
        if shorter[short_at] == longer[long_at] {
            short_at += 1;
            long_at += 1;
        } else if skipped {
            return false;
        } else {
            skipped = true;
            long_at += 1;
        }
    }
    true
}

fn name_is(token: &Token, expected: &str) -> bool {
    matches!(&token.tok, Tok::Name { name } if name == expected)
}

fn text_of<'a>(source: &'a str, tokens: &[Token]) -> &'a str {
    &source[tokens[0].span.start..tokens[tokens.len() - 1].span.end]
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::transpile;

    fn converted(source: &str, level: SyntaxLevel, language: Language) -> Conversion {
        convert_python(source, level, language).unwrap()
    }

    #[test]
    fn advanced_conversion_is_byte_identical() {
        let source = "name = input(\"Name? \" )\nprint(name)\n";
        assert_eq!(
            converted(source, SyntaxLevel::Advanced, Language::Korean),
            Conversion {
                source: source.to_string(),
                changed_lines: 0,
            }
        );
    }

    #[test]
    fn converts_sentence_file_reads_and_writes_and_round_trips() {
        let source = concat!(
            "x = open(\"notes.txt\").read()\n",
            "open(\"out.txt\", \"w\").write(\"hello\")\n",
            "memo = Path(\"data.json\").read_text()\n",
            "Path(\"out2.txt\").write_text(점수)\n",
            "y = open(\"x.txt\").readlines()\n",
        );
        assert_eq!(
            converted(source, SyntaxLevel::Sentence, Language::English).source,
            concat!(
                "read \"notes.txt\" into x\n",
                "write \"hello\" to \"out.txt\"\n",
                "read \"data.json\" into memo\n",
                "write 점수 to \"out2.txt\"\n",
                // The last line has no file sentence of its own, so it is
                // saved the ordinary way: a name and a piece of Python.
                "set y to open(\"x.txt\").readlines()\n",
            )
        );
        assert_eq!(
            converted(source, SyntaxLevel::Sentence, Language::Korean).source,
            concat!(
                "x에 \"notes.txt\" 읽어서\n",
                "\"out.txt\" 파일에 \"hello\"를 저장해\n",
                "memo에 \"data.json\" 읽어서\n",
                "\"out2.txt\" 파일에 점수를 저장해\n",
                "y는 open(\"x.txt\").readlines()\n",
            )
        );
        // The converted sentence source is valid NME. An undefined name like
        // `점수` in a one-line snippet interpolates as literal text, which is
        // the documented sentence behavior; defined names round-trip exactly.
        let converted_en = converted(source, SyntaxLevel::Sentence, Language::English).source;
        assert_eq!(
            transpile(&converted_en).unwrap(),
            concat!(
                "x = __import__(\"pathlib\").Path(\"notes.txt\").read_text()\n",
                "__import__(\"pathlib\").Path(\"out.txt\").write_text(\"hello\")\n",
                "memo = __import__(\"pathlib\").Path(\"data.json\").read_text()\n",
                "__import__(\"pathlib\").Path(\"out2.txt\").write_text(\"점수\")\n",
                "y = open(\"x.txt\").readlines()\n",
            )
        );
    }

    #[test]
    fn beginner_conversion_keeps_file_io_as_python() {
        // Reading a file has no beginner sentence, so the call itself stays
        // exactly as it was; only the saving word around it changes.
        let source = "x = open(\"notes.txt\").read()\n";
        assert_eq!(
            converted(source, SyntaxLevel::Beginner, Language::English).source,
            "save x to open(\"notes.txt\").read()\n"
        );
    }

    #[test]
    fn converts_the_safe_beginner_subset_in_both_languages() {
        let source = concat!(
            "name = input(\"Name? \")\n",
            "if name:\n",
            "    print(name)\n",
            "for _ in range(2):\n",
            "    print(\"Hi\")\n",
        );
        assert_eq!(
            converted(source, SyntaxLevel::Beginner, Language::English).source,
            concat!(
                "ask name, \"Name? \"\n",
                "if name:\n",
                "    say name\n",
                "2 times:\n",
                "    say \"Hi\"\n",
            )
        );
        assert_eq!(
            converted(source, SyntaxLevel::Beginner, Language::Korean).source,
            concat!(
                "물어봐 name, \"Name? \"\n",
                "if name:\n",
                "    말해 name\n",
                "2 번:\n",
                "    말해 \"Hi\"\n",
            )
        );
    }

    #[test]
    /// A block closed by the indentation under a `:` keeps its `:`, and one
    /// closed by `end` keeps its `end`. Which way a file closes its blocks is
    /// not the tidier's to change: a header that loses its mark leaves the
    /// lines under it closing nothing.
    fn converts_python_and_keeps_the_way_its_blocks_close() {
        let source = concat!(
            "name = input(\"What is your name?\")\n",
            "if name:\n",
            "    print(\"Hello, world!\")\n",
            "for _ in range(2):\n",
            "    print(name)\n",
        );
        let result = converted(source, SyntaxLevel::Sentence, Language::Korean);
        assert_eq!(
            result.source,
            concat!(
                "name을 물어봐 \"What is your name?\"\n",
                "if name:\n",
                "    Hello, world! 말해줘\n",
                "2번 반복해:\n",
                "    name 말해줘\n",
            )
        );
        assert_eq!(result.changed_lines, 4);
        assert!(transpile(&result.source).is_ok());
    }

    #[test]
    fn sentence_conversion_handles_numeric_input_and_assignments() {
        let source = "answer = 7\nguess = int(input(\"Guess\"))\nprint(guess)\n";
        assert_eq!(
            converted(source, SyntaxLevel::Sentence, Language::English).source,
            "set answer to 7\nask number guess \"Guess\"\nshow guess\n"
        );
    }

    #[test]
    fn sentence_conversion_keeps_string_and_prompt_semantics() {
        let source = "name = \"Ada\"\nquestion = input(\"Name?\")\nprint(\"Hello name\")\n";
        let result = converted(source, SyntaxLevel::Sentence, Language::English);
        assert_eq!(
            result.source,
            // The message keeps its quotes: `name` is a name the program
            // makes on the line above, so `show Hello name` would print what
            // is in it. A plainer spelling is what the tidier falls back to.
            "set name to Ada\nask question \"Name?\"\nshow \"Hello name\"\n"
        );
        assert_eq!(
            transpile(&result.source).unwrap(),
            "name = \"Ada\"\nquestion = input(\"Name?\")\nprint(\"Hello name\")\n"
        );
    }

    #[test]
    fn unsupported_python_stays_as_advanced_syntax() {
        let source = "while ready:\n    value += 1\nprint(value, end='')\n";
        let result = converted(source, SyntaxLevel::Sentence, Language::English);
        assert_eq!(result.source, source);
        assert_eq!(result.changed_lines, 0);
    }

    #[test]
    fn sentence_conversion_does_not_treat_unresolved_bare_names_as_text() {
        let source = "print(external)\nvalue = input(prompt)\ncopy = external\n";
        let result = converted(source, SyntaxLevel::Sentence, Language::English);
        assert_eq!(result.source, source);
        assert_eq!(transpile(&result.source).unwrap(), source);
        assert_eq!(result.changed_lines, 0);
    }

    #[test]
    fn skips_every_multi_physical_line_statement_without_changing_line_count() {
        let source = concat!(
            "value = (\n",
            "    1 + 2\n",
            ")\n",
            "print(\n",
            "    \"hello\"\n",
            ")\n",
            "text = \"\"\"one\n",
            "two\"\"\"\n",
            "print(\\\n",
            "    \"continued\")\n",
            "print(\"tail continued\") \\\n",
            "\n",
            "print(\"done\")  # keep this comment\n",
        );
        let result = converted(source, SyntaxLevel::Sentence, Language::English);
        assert_eq!(
            result.source,
            concat!(
                "value = (\n",
                "    1 + 2\n",
                ")\n",
                "print(\n",
                "    \"hello\"\n",
                ")\n",
                "text = \"\"\"one\n",
                "two\"\"\"\n",
                "print(\\\n",
                "    \"continued\")\n",
                "print(\"tail continued\") \\\n",
                "\n",
                "show done  # keep this comment\n",
            )
        );
        assert_eq!(result.changed_lines, 1);
        assert_eq!(
            result.source.bytes().filter(|byte| *byte == b'\n').count(),
            source.bytes().filter(|byte| *byte == b'\n').count()
        );
    }

    #[test]
    fn unsafe_print_shapes_stay_as_python_at_every_easier_level() {
        let source = concat!(
            "print(lambda: 1)\n",
            "print(item.value)\n",
            "print(items[0])\n",
            "print(make())\n",
            "print((1, 2))\n",
            "print(value := 1)\n",
            "print(left and right)\n",
            "print(left or right)\n",
            "print(not value)\n",
            "print(item in items)\n",
            "print(item not in items)\n",
            "print(left is right)\n",
            "print(left is not right)\n",
            "print(left | right)\n",
            "print(left & right)\n",
            "print(left ^ right)\n",
            "print(left << right)\n",
            "print(left >> right)\n",
            "print(left @ right)\n",
            "print(~left)\n",
            "print(left if flag else right)\n",
            "print(*items)\n",
            "print(value, end=\"\")\n",
            "print(**options)\n",
        );
        for level in [SyntaxLevel::Beginner, SyntaxLevel::Sentence] {
            let result = converted(source, level, Language::English);
            // Since 2026-08-20 the converter reads a line back into the
            // statement that would have written it and proves the reading by
            // lowering it again, so an expression it has no words for is
            // simply put after the output word. What must not change is the
            // program, and that is what is checked.
            assert_eq!(transpile(&result.source).unwrap(), source);
            // The shapes with no output word at all — a tuple, a walrus, a
            // starred call, a keyword argument — have no sentence to be put
            // in and stay exactly as they were.
            for line in [
                "print((1, 2))\n",
                "print(value := 1)\n",
                "print(*items)\n",
                "print(value, end=\"\")\n",
                "print(**options)\n",
            ] {
                assert!(result.source.contains(line), "{line} moved");
            }
        }
    }

    #[test]
    fn ambiguous_assignments_stay_as_python() {
        let source = concat!(
            "copy = original\n",
            "callback = lambda: 1\n",
            "attribute = item.value\n",
            "element = items[0]\n",
            "called = make()\n",
            "pair = (1, 2)\n",
            "walrus = (inner := 1)\n",
            "combined = left and right\n",
            "member = item in items\n",
            "bits = left | right\n",
            "choice = left if flag else right\n",
            "left = right = 1\n",
            "left += 1\n",
        );
        for language in [Language::English, Language::Korean] {
            let result = converted(source, SyntaxLevel::Sentence, language);
            // A name saved a value keeps its saving word whatever the value
            // is; what may never change is the value itself.
            assert_eq!(transpile(&result.source).unwrap(), source);
            // These four have no saving sentence at all: two names at once,
            // a change in place, a name the line only copies, and a `lambda`
            // whose colon would close a block.
            for line in [
                "copy = original\n",
                "callback = lambda: 1\n",
                "left = right = 1\n",
                "left += 1\n",
            ] {
                assert!(result.source.contains(line), "{line} moved");
            }
        }
    }

    #[test]
    fn unsafe_conditions_and_range_counts_stay_as_python() {
        let source = concat!(
            "if check():\n    pass\n",
            "if item.value:\n    pass\n",
            "if items[0]:\n    pass\n",
            "if (left, right):\n    pass\n",
            "if (value := 1):\n    pass\n",
            "if left and right:\n    pass\n",
            "if item in items:\n    pass\n",
            "if left | right:\n    pass\n",
            "if left if flag else right:\n    pass\n",
            "for _ in range(make()):\n    pass\n",
            "for _ in range(counts[0]):\n    pass\n",
            "for _ in range(start, stop):\n    pass\n",
        );
        let result = converted(source, SyntaxLevel::Sentence, Language::English);
        assert_eq!(transpile(&result.source).unwrap(), source);
        // A condition NME has no words for keeps its Python, and so does a
        // count that starts somewhere other than zero: `repeat start, stop
        // times` is not a sentence anybody means.
        for line in [
            "if (left, right):\n",
            "if (value := 1):\n",
            "if left if flag else right:\n",
            "for _ in range(start, stop):\n",
        ] {
            assert!(result.source.contains(line), "{line} moved");
        }
    }

    #[test]
    fn input_conversion_accepts_only_one_safe_positional_prompt() {
        let source = concat!(
            "plain = input(\"Prompt\")\n",
            "keyword = input(prompt=\"Prompt\")\n",
            "unpacked = input(**options)\n",
            "starred = input(*prompts)\n",
            "trailing = input(\"Prompt\",)\n",
            "based = int(input(\"Number\"), 10)\n",
            "based_keyword = int(input(\"Number\"), base=10)\n",
            "nested_keyword = int(input(prompt=\"Number\"))\n",
        );
        let result = converted(source, SyntaxLevel::Sentence, Language::English);
        assert_eq!(
            result.source,
            concat!(
                "ask plain \"Prompt\"\n",
                "keyword = input(prompt=\"Prompt\")\n",
                // None of these is a question a sentence can carry, so the
                // call stays as it was; only the saving word around it can
                // change, and that changes nothing about the program.
                "set unpacked to input(**options)\n",
                "set starred to input(*prompts)\n",
                "set trailing to input(\"Prompt\",)\n",
                "set based to int(input(\"Number\"), 10)\n",
                "set based_keyword to int(input(\"Number\"), base=10)\n",
                "nested_keyword = int(input(prompt=\"Number\"))\n",
            )
        );
        assert_eq!(result.changed_lines, 6);
    }

    #[test]
    fn ordinary_random_import_is_never_replaced_by_the_bundled_adapter() {
        let source = "import random\nprint(\"ok\")\n";
        let result = converted(source, SyntaxLevel::Sentence, Language::Korean);
        assert_eq!(result.source, "import random\nok 말해줘\n");
        assert_eq!(result.changed_lines, 1);
    }

    #[test]
    fn safe_sentence_conversion_round_trips_with_comments() {
        let source = concat!(
            "answer = 7  # constant\n",
            "name = input(\"Name? \")  # prompt\n",
            "print(name)  # answer\n",
            "total = answer + 2\n",
            "print(total + 1)\n",
        );
        for language in [Language::English, Language::Korean] {
            let result = converted(source, SyntaxLevel::Sentence, language);
            assert_eq!(result.changed_lines, 5);
            assert_eq!(transpile(&result.source).unwrap(), source);
        }
    }

    #[test]
    fn later_bindings_do_not_make_an_earlier_name_look_safe() {
        let source = "print(later)\nlater = 1\n";
        let result = converted(source, SyntaxLevel::Sentence, Language::English);
        assert_eq!(result.source, "print(later)\nset later to 1\n");
        assert_eq!(transpile(&result.source).unwrap(), source);
        assert_eq!(result.changed_lines, 1);
    }

    #[test]
    fn sentence_input_keeps_a_variable_prompt_as_python() {
        // A question whose words come out of a name is not one a sentence can
        // ask, so that line stays as it was. The line above it is an ordinary
        // save and is written as one.
        let source = "prompt = \"Name?\"\nanswer = input(prompt)\n";
        let result = converted(source, SyntaxLevel::Sentence, Language::English);
        assert_eq!(result.source, "set prompt to Name?\nanswer = input(prompt)\n");
        assert_eq!(transpile(&result.source).unwrap(), source);
        assert_eq!(result.changed_lines, 1);
    }

    #[test]
    fn sentence_assignment_keeps_target_first_action_names_as_python() {
        for target in [
            "ask",
            "Prompt",
            "question",
            "number",
            "numeric",
            "숫자",
            "물어봐",
            "입력받아주세요",
        ] {
            let source = format!("{target} = 1\n");
            for language in [Language::English, Language::Korean] {
                let result = converted(&source, SyntaxLevel::Sentence, language);
                // A name that reads as an action word may still be saved into
                // — what may never change is what the line does.
                assert_eq!(
                    transpile(&result.source).unwrap(),
                    source,
                    "target {target}"
                );
            }
        }
    }

    #[test]
    fn bare_name_output_does_not_leak_bindings_across_scopes() {
        let source = "def make_value():\n    scoped = 1\nprint(scoped)\n";
        for level in [SyntaxLevel::Beginner, SyntaxLevel::Sentence] {
            for language in [Language::English, Language::Korean] {
                let result = converted(source, level, language);
                assert!(result.source.ends_with("print(scoped)\n"));
                assert_eq!(transpile(&result.source).unwrap(), source);
            }
        }
    }

    #[test]
    fn python_identifier_aliases_never_gain_an_nme_literal_or_random_meaning() {
        for name in [
            "true",
            "FALSE",
            "none",
            "null",
            "참",
            "거짓",
            "없음",
            "pick",
            "pink",
            "randomchoice",
            "랜덤선택",
            "골라",
        ] {
            let source = format!("{name} = 2\nresult = 1 + {name}\nprint(1 + {name})\n");
            for language in [Language::English, Language::Korean] {
                let result = converted(&source, SyntaxLevel::Sentence, language);
                assert_eq!(transpile(&result.source).unwrap(), source, "name {name}");
            }
        }
    }

    #[test]
    fn repeat_conversion_round_trips_identifier_counts_at_every_surface() {
        let source = concat!(
            "count = 2\n",
            "for _ in range(count):\n",
            "    print(\"again\")\n",
            "for _ in range(1 + count):\n",
            "    print(\"again\")\n",
        );
        for level in [SyntaxLevel::Beginner, SyntaxLevel::Sentence] {
            for language in [Language::English, Language::Korean] {
                let result = converted(source, level, language);
                assert_eq!(transpile(&result.source).unwrap(), source);
                if language == Language::Korean {
                    assert!(result.source.contains("count 번"));
                    assert!(result.source.contains("1 + count 번"));
                }
            }
        }

        for count in ["times", "번"] {
            let source = format!("{count} = 2\nfor _ in range({count}):\n    pass\n");
            for level in [SyntaxLevel::Beginner, SyntaxLevel::Sentence] {
                for language in [Language::English, Language::Korean] {
                    let result = converted(&source, level, language);
                    assert!(!result.source.contains("repeat times times"));
                    assert_eq!(transpile(&result.source).unwrap(), source);
                }
            }
        }
    }

    #[test]
    fn input_modifier_targets_and_unsafe_arguments_stay_python_in_every_surface() {
        for target in ["number", "numeric", "숫자", "숫자로", "수로"] {
            let source = format!("{target} = input(\"Prompt\")\n");
            for level in [SyntaxLevel::Beginner, SyntaxLevel::Sentence] {
                for language in [Language::English, Language::Korean] {
                    let result = converted(&source, level, language);
                    // The English question puts the word `number` where a
                    // modifier goes and cannot be written; the Korean one
                    // names its target first and can. Either way the program
                    // is the one that came in.
                    assert_eq!(
                        transpile(&result.source).unwrap(),
                        source,
                        "target {target}"
                    );
                }
            }
        }

        let source = concat!(
            "keyword = input(prompt=\"Prompt\")\n",
            "unpacked = input(**options)\n",
            "starred = input(*prompts)\n",
            "trailing = input(\"Prompt\",)\n",
            "based = int(input(\"Number\"), 10)\n",
            "based_keyword = int(input(\"Number\"), base=10)\n",
            "nested_keyword = int(input(prompt=\"Number\"))\n",
        );
        for level in [SyntaxLevel::Beginner, SyntaxLevel::Sentence] {
            for language in [Language::English, Language::Korean] {
                let result = converted(source, level, language);
                // None of these questions can be written as one, so the call
                // is left exactly as it stands; the saving word around it may
                // change, and that changes nothing about the program.
                assert_eq!(transpile(&result.source).unwrap(), source);
                for line in ["input(**options)", "input(*prompts)", "input(\"Prompt\",)"] {
                    assert!(result.source.contains(line), "{line} moved");
                }
            }
        }
    }

    #[test]
    fn condition_names_that_look_conversational_stay_python() {
        for name in ["then", "them", "exists", "true", "참", "이름은"] {
            let source = format!("{name} = 1\nif {name}:\n    pass\n");
            for level in [SyntaxLevel::Beginner, SyntaxLevel::Sentence] {
                for language in [Language::English, Language::Korean] {
                    let result = converted(&source, level, language);
                    assert_eq!(transpile(&result.source).unwrap(), source, "name {name}");
                }
            }
        }

        for name in ["then", "them", "exists", "true", "참"] {
            let source = format!("{name} = 1\nif {name} + 1:\n    pass\n");
            for level in [SyntaxLevel::Beginner, SyntaxLevel::Sentence] {
                for language in [Language::English, Language::Korean] {
                    let result = converted(&source, level, language);
                    assert_eq!(transpile(&result.source).unwrap(), source, "name {name}");
                }
            }
        }
    }

    #[test]
    fn symbolic_comparisons_still_convert_and_keep_their_python_meaning() {
        let source = "score = 2\nif score > 1:\n    print(\"ok\")\n";
        let expected = "score = 2\nif (score > 1):\n    print(\"ok\")\n";
        for level in [SyntaxLevel::Beginner, SyntaxLevel::Sentence] {
            for language in [Language::English, Language::Korean] {
                let result = converted(source, level, language);
                assert_eq!(transpile(&result.source).unwrap(), expected);
            }
        }
    }

    #[test]
    fn rejects_invalid_python_before_conversion() {
        let errors =
            convert_python("if broken\n", SyntaxLevel::Sentence, Language::English).unwrap_err();
        assert_eq!(errors.len(), 1);
        assert!(errors[0].message.contains("not valid"));
        assert!(errors[0].hint.is_some());
    }
}
