# -*- coding: utf-8 -*-
"""Ordinary sentences built out of the words the date module binds.

None of these is a program. They are the everyday senses of `date`, `today`,
`now`, `year`, `month`, `weekday`, `날짜`, `오늘`, `지금`, `올해`, `이번달`,
`요일`, `며칠` — a note to self, a line of a message, a line of a story. Every
one must compile to `print("<the sentence>")`, character for character, whether
or not the program has opened the date module.

Grouped only for reading; `date_words.py` treats each list as one list.
"""

# --------------------------------------------------------------------- English

_DATE = [
    "What is the date today?",
    "I forgot to write the date on the form.",
    "The date on the receipt is smudged.",
    "Please put the date at the top of the page.",
    "We agreed on a date for the wedding.",
    "The date of the meeting has moved again.",
    "Check the date before you eat it.",
    "She circled the date on the calendar.",
    "No date has been set for the repairs.",
    "The date printed on the ticket is wrong.",
    "I keep getting the date muddled up.",
    "He asked me out on a date.",
    "The closing date is the end of the month.",
    "That date works for everyone except Tom.",
    "Write your name and the date in the box.",
    "The date of birth field cannot be empty.",
    "We picked a date and booked the hall.",
    "The date slipped my mind entirely.",
    "Their anniversary date is easy to remember.",
    "The date stamp had faded away.",
    "I will confirm the date by Friday.",
    "A later date would suit me better.",
    "The delivery date keeps being pushed back.",
    "Put the date in the subject line please.",
    "The date was crossed out and rewritten.",
    "There is a date palm in the garden.",
    "She ate a date with her coffee.",
    "The exam date has finally been announced.",
    "Nobody remembers the exact date any more.",
    "Keep a note of the date you sent it.",
]

_TODAY = [
    "It is very cold today.",
    "I am not going out today.",
    "Today was a long day.",
    "We had rice for lunch today.",
    "Today is the first day of term.",
    "Nothing much happened today.",
    "I finished the book today.",
    "Today the bus was half an hour late.",
    "She looks much better today.",
    "The shop is closed today.",
    "I will call you later today.",
    "Today feels like a Monday somehow.",
    "The garden looks lovely today.",
    "We walked five miles today.",
    "Today I learned something new.",
    "He is off work today with a cold.",
    "Today is not the day for arguing.",
    "I have three meetings today.",
    "Today the sea was completely flat.",
    "My knee is playing up again today.",
    "Today marks a whole year since we moved.",
    "There is no post today.",
    "Today I am grateful for small things.",
    "The children were angels today.",
    "I burned the toast twice today.",
    "Today the queue went round the corner.",
    "Not today, thank you.",
    "Today would be a good day for a swim.",
    "Everything went wrong today.",
    "Today I finally rang the dentist.",
]

_NOW = [
    "I will do it now.",
    "Now is not a good time.",
    "She is on her way now.",
    "Right now I just want a cup of tea.",
    "Now the rain has stopped.",
    "We are ready now.",
    "He lives in Bristol now.",
    "Now I understand what she meant.",
    "The kettle is boiling now.",
    "Now then, where were we?",
    "It is too late now.",
    "Now that I think about it, she was right.",
    "The baby is asleep now.",
    "I am reading it now.",
    "Now everything makes sense.",
    "Come on now, be sensible.",
    "The train is leaving now.",
    "I am not hungry now.",
    "Now would be the moment to say something.",
    "By now she will have landed.",
    "Every now and then I miss the old house.",
    "Now go and wash your hands.",
    "I feel much calmer now.",
    "The light is better now.",
    "Now I have to start all over again.",
]

_YEAR_MONTH = [
    "It has been a difficult year.",
    "This year the apples came early.",
    "Last year we went to Wales.",
    "The school year starts in September.",
    "A whole year has gone by.",
    "Every year the same argument.",
    "The year is nearly over.",
    "She turns ten this year.",
    "That was the best year of my life.",
    "The year of the flood is still talked about.",
    "It rained for a whole month.",
    "This month has flown by.",
    "The rent is due at the end of the month.",
    "Next month we move house.",
    "A month is not long enough.",
    "The month of May is my favourite.",
    "He was ill for a month.",
    "We saved up for a month.",
    "Last month the roof leaked again.",
    "Give it a month and see.",
]

_WEEKDAY_DAYS = [
    "I can never remember which weekday it is.",
    "The museum is free on a weekday.",
    "A weekday morning is the quietest time.",
    "Weekday trains are always packed.",
    "She only works on a weekday.",
    "Any weekday except Thursday would do.",
    "Weekday evenings are for homework.",
    "The pool is emptier on a weekday.",
    "It costs less on a weekday.",
    "Weekday parking is impossible here.",
    "Come back in a few days after the swelling goes down.",
    "Two days after the storm the power came back.",
    "The day of the month is printed on the label.",
    "It arrived three days after I ordered it.",
    "Days after the party we were still tidying.",
]

_MIXED_EN = [
    "The date today is on the whiteboard.",
    "Now the date has changed again.",
    "Today is the last weekday of the month.",
    "By this time next year we will have forgotten the date.",
    "Now and then I check the date on my phone.",
    "Today, right now, this month, nothing is going to plan.",
    "The date and the weekday never seem to agree.",
    "Today the month changed and I did not notice.",
    "Every year I write the wrong year for a month.",
    "Now put the date and your name at the top.",
    "Today I will use the calendar properly.",
    "Use the date on the label, not the one on the box.",
    "I use a paper diary for dates and a phone for everything else.",
    "The list of dates is in the drawer.",
    "Text me the date when you know it.",
    "A month of weekdays with nothing in the diary.",
    "The year, the month and the day are all in the file name.",
    "Set the date on the oven clock before you go.",
    "Today the weather turned and now it is freezing.",
    "The date is fine but the time is not.",
    "Now I have written the wrong year again.",
    "Today I found a receipt from last year.",
    "The month before last we had no rain at all.",
    "She works weekdays and I work weekends.",
    "Now everyone wants a different date.",
    "The date, the place and the time are all on the card.",
    "Today the shop had no bread and no milk.",
    "That was a year ago now.",
    "Now the year is nearly over and I am no wiser.",
    "Whatever the date, we will be there.",
    "The weekday rate is cheaper than the weekend one.",
    "I will pick a date and stick to it this time.",
    "Today has been the shortest day of the year.",
    "Now the days are getting longer again.",
    "The month of the move was the worst month of all.",
]

ENGLISH = _DATE + _TODAY + _NOW + _YEAR_MONTH + _WEEKDAY_DAYS + _MIXED_EN

# ---------------------------------------------------------------------- Korean

_KO_DATE = [
    "날짜를 잘못 적었습니다",
    "약속 날짜를 다시 정했습니다",
    "날짜가 아직 정해지지 않았습니다",
    "영수증에 찍힌 날짜가 흐릿합니다",
    "서류 맨 위에 날짜를 적어 주세요",
    "회의 날짜가 또 밀렸습니다",
    "먹기 전에 날짜를 확인하세요",
    "달력에 날짜를 동그라미 쳐 두었습니다",
    "그 날짜에는 이미 다른 약속이 있습니다",
    "표에 인쇄된 날짜가 틀렸습니다",
    "날짜를 자꾸 헷갈립니다",
    "마감 날짜는 이번 주 금요일입니다",
    "그 날짜면 모두 괜찮다고 합니다",
    "이름과 날짜를 칸에 적어 주세요",
    "생년월일 날짜는 비워 둘 수 없습니다",
    "날짜를 정하고 장소를 예약했습니다",
    "날짜가 완전히 기억나지 않습니다",
    "결혼기념일 날짜는 외우기 쉽습니다",
    "도장 날짜가 지워져 있었습니다",
    "날짜는 금요일까지 알려 드리겠습니다",
    "조금 늦은 날짜가 저는 더 편합니다",
    "배송 날짜가 계속 미뤄집니다",
    "제목에 날짜를 넣어 주세요",
    "날짜가 두 줄로 그어져 있었습니다",
    "시험 날짜가 드디어 나왔습니다",
]

_KO_TODAY = [
    "오늘 날씨가 좋네요",
    "오늘은 하루가 참 길었습니다",
    "오늘 점심은 김치찌개였습니다",
    "오늘은 개학 첫날입니다",
    "오늘은 별일 없었습니다",
    "오늘 책을 다 읽었습니다",
    "오늘 버스가 삼십 분이나 늦었습니다",
    "오늘은 훨씬 나아 보입니다",
    "가게가 오늘 문을 닫았습니다",
    "오늘 늦게 다시 전화드리겠습니다",
    "오늘은 어쩐지 월요일 같습니다",
    "오늘 정원이 참 예쁩니다",
    "오늘 오 킬로미터를 걸었습니다",
    "오늘 새로운 것을 하나 배웠습니다",
    "그는 감기로 오늘 쉽니다",
    "오늘은 다툴 날이 아닙니다",
    "오늘 회의가 세 개나 있습니다",
    "오늘 바다가 아주 잔잔했습니다",
    "오늘도 무릎이 시큰거립니다",
    "오늘로 이사 온 지 딱 일 년입니다",
    "오늘은 우편물이 없습니다",
    "오늘은 작은 것들이 고맙습니다",
    "아이들이 오늘 참 얌전했습니다",
    "오늘 빵을 두 번이나 태웠습니다",
    "오늘은 줄이 모퉁이까지 늘어섰습니다",
    "오늘은 됐습니다 고맙습니다",
    "오늘은 수영하기 좋은 날입니다",
    "오늘은 되는 일이 하나도 없었습니다",
    "오늘 드디어 치과에 전화했습니다",
    "오늘 저녁은 밖에서 먹기로 했습니다",
]

_KO_NOW = [
    "지금 가고 있습니다",
    "지금은 때가 아닙니다",
    "지금 막 도착했습니다",
    "지금은 차 한 잔이면 충분합니다",
    "지금 비가 그쳤습니다",
    "이제 준비가 다 되었습니다",
    "그는 지금 부산에 삽니다",
    "지금에서야 그 말뜻을 알겠습니다",
    "주전자가 지금 끓고 있습니다",
    "지금 어디까지 이야기했지요",
    "지금은 너무 늦었습니다",
    "지금 생각해 보니 그 말이 맞았습니다",
    "아기가 지금 자고 있습니다",
    "지금 읽고 있는 중입니다",
    "지금은 모든 것이 이해가 됩니다",
    "지금 기차가 떠나고 있습니다",
    "지금은 배가 고프지 않습니다",
    "지금이 말할 때입니다",
    "지금쯤이면 도착했을 것입니다",
    "지금 손부터 씻고 오세요",
    "지금은 마음이 훨씬 편합니다",
    "지금이 빛이 제일 좋습니다",
    "지금부터 다시 시작해야 합니다",
    "지금 통화 괜찮으신가요",
    "지금 하는 일이 즐겁습니다",
]

_KO_YEAR_MONTH = [
    "올해도 잘 부탁드립니다",
    "올해는 참 힘든 해였습니다",
    "올해는 사과가 일찍 나왔습니다",
    "작년에는 강원도에 갔습니다",
    "올해가 벌써 다 갔습니다",
    "해마다 같은 이야기입니다",
    "올해 아이가 열 살이 됩니다",
    "올해는 눈이 많이 왔습니다",
    "올해 목표를 다시 적어 봤습니다",
    "올해 안에는 끝내고 싶습니다",
    "이번 달은 정말 빨리 갔습니다",
    "월세는 이번 달 말에 냅니다",
    "다음 달에 이사를 갑니다",
    "한 달로는 부족합니다",
    "오월이 저는 제일 좋습니다",
    "그는 한 달 동안 아팠습니다",
    "한 달 동안 돈을 모았습니다",
    "지난달에 지붕이 또 샜습니다",
    "한 달만 지켜보기로 했습니다",
    "이번달 가계부를 아직 못 썼습니다",
]

_KO_WEEKDAY_DAYS = [
    "요일을 자꾸 헷갈립니다",
    "박물관은 평일 요일에 무료입니다",
    "무슨 요일이 편하신가요",
    "요일마다 반찬이 다릅니다",
    "그 수업은 요일이 바뀌었습니다",
    "요일과 시간을 적어 주세요",
    "요일별로 당번을 정했습니다",
    "요일 감각이 완전히 사라졌습니다",
    "무슨 요일인지도 모르고 지냈습니다",
    "요일에 따라 값이 다릅니다",
    "며칠 뒤에 다시 오세요",
    "며칠 전에 편지를 받았습니다",
    "며칠 동안 잠을 못 잤습니다",
    "며칠 뒤면 괜찮아질 것입니다",
    "주문한 지 며칠 뒤에 도착했습니다",
    "오늘일자로 계약이 끝났습니다",
    "달이 참 밝습니다",
    "일주일이 어떻게 갔는지 모르겠습니다",
    "이번 주는 유난히 길었습니다",
    "내일 다시 이야기합시다",
]

_KO_MIXED = [
    "오늘 날짜가 칠판에 적혀 있습니다",
    "지금 날짜가 또 바뀌었습니다",
    "오늘이 이번 달 마지막 평일입니다",
    "내년 이맘때면 날짜도 잊어버릴 것입니다",
    "가끔 지금 날짜를 휴대폰으로 확인합니다",
    "오늘도 지금도 이번 달도 계획대로 되는 것이 없습니다",
    "날짜와 요일이 도무지 맞지 않습니다",
    "오늘 달이 바뀐 것을 몰랐습니다",
    "해마다 한 달쯤은 연도를 틀리게 씁니다",
    "맨 위에 날짜와 이름을 적어 주세요",
    "오늘은 달력을 제대로 써 보겠습니다",
    "상자가 아니라 라벨의 날짜를 보세요",
    "날짜는 수첩에 적고 나머지는 휴대폰에 적습니다",
    "날짜 목록은 서랍에 있습니다",
    "날짜가 정해지면 문자로 알려 주세요",
    "약속 하나 없는 평일이 한 달 내내 이어졌습니다",
    "연도와 달과 날짜가 파일 이름에 다 들어 있습니다",
    "나가기 전에 오븐 시계의 날짜를 맞춰 두세요",
    "오늘 날이 바뀌더니 지금은 몹시 춥습니다",
    "날짜는 괜찮은데 시간이 안 됩니다",
    "지금 또 연도를 잘못 적었습니다",
    "오늘 작년 영수증을 하나 찾았습니다",
    "지지난달에는 비가 한 방울도 안 왔습니다",
    "그 사람은 평일에 일하고 저는 주말에 일합니다",
    "지금은 모두가 다른 날짜를 원합니다",
    "날짜와 장소와 시간이 카드에 다 적혀 있습니다",
    "오늘 가게에 빵도 우유도 없었습니다",
    "그게 벌써 일 년 전 일입니다",
    "이제 올해도 거의 다 갔는데 나아진 것이 없습니다",
    "날짜가 언제가 되든 저희는 갑니다",
    "평일 요금이 주말 요금보다 쌉니다",
    "이번에는 날짜를 정하면 꼭 지키겠습니다",
    "오늘이 올해 가장 짧은 날이었습니다",
    "이제 해가 다시 길어지고 있습니다",
    "이사한 달이 올해 중 가장 힘든 달이었습니다",
]

KOREAN = _KO_DATE + _KO_TODAY + _KO_NOW + _KO_YEAR_MONTH + _KO_WEEKDAY_DAYS + _KO_MIXED
