# -*- coding: utf-8 -*-
"""English prose corpus — sentences that must print themselves, word for word.

None of these is a program and none of them is a mistake. They are ordinary
English sentences a person really types into a file: a line of a story, a note
to themselves, a comment they forgot to mark, a line of game dialogue, a
message to a player. Every one of them should compile to

    print("<the sentence>")

with the string identical to the sentence, character for character.

The list is grouped only for reading; the measurement treats it as one list.
"""

# 1. Sentences that open with a word the language also uses as a command.
COMMAND_FIRST_WORD = [
    "show me the way home",
    "show him what you found in the attic",
    "Show your work before you hand it in.",
    "ask your teacher about the field trip",
    "Ask nicely and she might say yes.",
    "ask me anything you like",
    "set the table for four people",
    "Set your alarm for the early train.",
    "set aside an hour for reading",
    "wait for the rain to stop",
    "Wait here until I come back.",
    "wait a moment, I heard something",
    "count the candles on the cake",
    "Count me in for Saturday.",
    "count your blessings tonight",
    "pick a flower from the garden",
    "Pick up your coat on the way out.",
    "pick a card and remember it",
    "choose the door on the left",
    "Choose kindness whenever you can.",
    "choose whichever one you prefer",
    "add a little salt to the soup",
    "Add your name to the sign up sheet.",
    "add some colour to the drawing",
    "remove your shoes at the door",
    "Remove the lid slowly.",
    "remove the sticker before washing",
    "sort the laundry into two piles",
    "Sort out your desk this weekend.",
    "sort the photographs by year",
    "clear the table after dinner",
    "Clear a path through the snow.",
    "clear your head with a walk",
    "draw a circle around the answer",
    "Draw the curtains before bed.",
    "draw me a picture of your house",
    "write your name on the envelope",
    "Write to me when you arrive.",
    "write it down before you forget",
    "read the instructions twice",
    "Read to your children every night.",
    "read the label on the bottle",
    "store the jam in a cool place",
    "Store your bicycle in the shed.",
    "store the leftovers for tomorrow",
    "list your favourite films for me",
    "List the ingredients on the back.",
    "list everyone who came to the party",
    "repeat that once more, please",
    "Repeat after me.",
    "repeat the chorus a little louder",
    "stop worrying about the weather",
    "Stop at the corner shop.",
    "stop pretending you did not hear",
    "skip breakfast if you are late",
    "Skip the boring chapters.",
    "skip stones across the pond",
    "end of the road",
    "End the letter with your name.",
    "start the engine slowly",
    "Start again from the beginning.",
    "start with something small",
    "story of a small town doctor",
    "Story time is at seven.",
    "chance meeting on a rainy street",
    "Chance would be a fine thing.",
    "say something nice to your brother",
    "tell me about your day",
    "print the photograph in black and white",
    "display your medals on the shelf",
    "make yourself at home",
    "put the kettle on",
    "get well soon",
    "save the last dance for me",
    "use the back door tonight",
    "input from the audience was mixed",
    "output of the factory fell again",
    "round the corner there is a bakery",
    "shuffle the cards and deal seven each",
    "remember to water the plants",
    "insert the key gently",
    "push the door, do not pull it",
    "pause and look at the sky",
    "sleep well tonight",
    "break the bread and share it",
    "quit while you are ahead",
    "raise your voice a little",
    "verify what he told you",
    "loop the ribbon around twice",
    "random acts of kindness matter",
    "when the lights went out we sang",
    "while the kettle boiled she read the letter",
    "if only she had said goodbye",
    "for the last time, close the window",
    "each of them told a different story",
    "print out the letter and post it",
    "check the mail before you leave",
    "open the window and let the air in",
    "close your eyes and count to ten",
    "return the book to the library",
    "call your grandmother on Sunday",
    "run for the bus, it is coming",
    "keep your promises",
    "hold my hand crossing the road",
    "wake me before the sun rises",
    "turn left at the church",
    "watch out for the loose step",
    "let me think about it",
    "log the miles you walked this week",
]

# 2. Numbers, percentages, units, times, prices, ordinals.
NUMBERS_AND_UNITS = [
    "There were 12 people waiting at the gate.",
    "The bread costs 3 pounds at the corner shop.",
    "She was 7 years old that summer.",
    "It rained for 40 days.",
    "About 60 percent of them agreed.",
    "The battery is at 15% and falling.",
    "The road climbs 400 metres in two miles.",
    "He weighed 82 kg after the season.",
    "The soup needs 250 ml of cream.",
    "The train leaves at 6:45 in the morning.",
    "We met at 9 o'clock outside the theatre.",
    "The meeting ran from 2pm until half past four.",
    "The ticket cost $17.50 including the booking fee.",
    "It was the 3rd time she had asked.",
    "He finished 2nd and was furious about it.",
    "This is the 1st letter I have written in years.",
    "The 21st of June is the longest day.",
    "Room 214 is at the end of the corridor.",
    "Chapter 5 is where the story turns.",
    "In 1974 the factory closed for good.",
    "The temperature dropped to minus 6 overnight.",
    "Three of the five windows were broken.",
    "Half of the cake was gone by noon.",
    "She ran the last kilometre in 4 minutes.",
    "The recipe serves 6 hungry people.",
    "Only 1 in 10 letters was ever answered.",
    "The hall seats 300 and it was full.",
    "The rent went up by 8 percent again.",
    "Flight 402 was delayed by two hours.",
    "He counted 99 sheep and gave up.",
]

# 3. Sentences built around is, are, was, has, to, from, in, of, with, and, or, not.
FUNCTION_WORDS = [
    "Today is a good day",
    "The kitchen is cold in the morning.",
    "My brother is a very slow reader.",
    "This is not what I ordered.",
    "There is nothing left to say.",
    "The children are asleep upstairs.",
    "The keys are on the hook by the door.",
    "We are late and it is my fault.",
    "It was a long walk back to the village.",
    "She was kinder than anyone expected.",
    "The letter was never sent.",
    "He has a way of arriving unannounced.",
    "The house has three chimneys and no heating.",
    "Nobody has seen him since Tuesday.",
    "I want to tell you something important.",
    "It is easy to forget how young she was.",
    "The path from the village to the sea is steep.",
    "A letter came from my aunt in Canada.",
    "The cat sleeps in the empty suitcase.",
    "There is a crack in the ceiling above the bed.",
    "The smell of rain on hot pavement is the best smell.",
    "A jug of milk stood on the windowsill.",
    "She left with nothing but a coat and a book.",
    "Tea with too much sugar is still tea.",
    "Bread and cheese was all we had.",
    "He packed slowly and carefully and said nothing.",
    "You can walk or you can take the bus.",
    "Tell me the truth or tell me nothing.",
    "I do not remember the name of the street.",
    "That is not how the story ends.",
]

# 4. Questions, imperatives, negations, full stops and question marks.
QUESTIONS_AND_COMMANDS = [
    "Where did you put my glasses?",
    "What time does the bakery open?",
    "Who left the gate open?",
    "Why is the dog on the sofa again?",
    "How much further is it?",
    "Are you coming with us?",
    "Is that really the last one?",
    "Did anyone remember the salt?",
    "Can you hear the sea from here?",
    "Would you like another cup?",
    "Shall we walk the long way home?",
    "Do you still write letters?",
    "Whose coat is this?",
    "Which one did you choose in the end?",
    "Have you eaten anything today?",
    "Please close the gate behind you.",
    "Do not touch the wet paint.",
    "Never leave the fire unattended.",
    "Mind the gap between the train and the platform.",
    "Be careful on the stairs, they are steep.",
]

# 5. Apostrophes — possessives and contractions.
APOSTROPHES = [
    "Don't forget your umbrella.",
    "It's raining again in the valley.",
    "I can't find the other glove.",
    "She won't be back before dark.",
    "We're going to be late for the film.",
    "They've painted the door bright blue.",
    "You'd think somebody would have noticed.",
    "He didn't mean it the way it sounded.",
    "That isn't the house I grew up in.",
    "There's a bird nesting in the chimney.",
    "The cat's bowl is empty again.",
    "My mother's handwriting is beautiful.",
    "The children's shoes were by the door.",
    "James's bicycle was still in the hall.",
    "The dog's bark woke the whole street.",
    "We left at six o'clock in the morning.",
    "It's the neighbour's cat, not ours.",
    "Who's going to tell her the news?",
    "Let's not talk about it tonight.",
    "I'd rather walk than wait for the bus.",
    "That's what she said at the funeral.",
    "The village's only shop closed last year.",
]

# 6. Commas, colons, semicolons, dashes, ellipses, brackets.
PUNCTUATION = [
    "First, we packed the car; then it started to rain.",
    "The rule is simple: nobody eats before grace.",
    "He had one talent: making people laugh.",
    "She waited, and waited, and finally went home.",
    "The garden was small — smaller than the photograph suggested.",
    "It was cold, dark, and very quiet.",
    "I thought about it for a long time...",
    "And then, suddenly, nothing.",
    "The house (the one with the red door) was for sale.",
    "Take the second turning (not the first) after the bridge.",
    "There were three things wrong: the roof, the boiler, and the neighbours.",
    "He said he would come; he never did.",
    "Well — that was unexpected.",
    "Two things mattered to her: the garden and the dog.",
    "Slowly, carefully, he lifted the lid.",
    "The answer, if there is one, is not in this book.",
    "Everything was fine... until it wasn't.",
    "We had bread, cheese, apples and a flask of tea.",
    "The town [population 400] has two pubs and no doctor.",
    "Stop; look; listen.",
]

# 7. Lines of a story — narration, dialogue, headings.
STORY_LINES = [
    "Chapter One",
    "Chapter Seven: The Long Winter",
    "Part Two",
    "Prologue",
    "The End",
    "Three years later",
    "Meanwhile, back at the harbour",
    "It was a dark and quiet evening in the village.",
    "The old man had not spoken since Thursday.",
    "Snow began to fall on the empty market square.",
    "Nobody in the house heard the front door close.",
    "The lamp flickered twice and went out.",
    "Outside, the wind pulled at the shutters.",
    "She read the letter twice and put it in the fire.",
    "The train pulled away and he did not wave.",
    "In the morning the boat was gone.",
    "Something moved in the long grass by the wall.",
    "He remembered the smell of his grandmother's kitchen.",
    "The village had one road and it went nowhere.",
    "Her hands shook as she opened the box.",
    "I never told anyone what I saw that night.",
    "Come with me, said the stranger.",
    "Not tonight, she said, and closed the door.",
    "I am not afraid of you, he whispered.",
    "\"Who is there?\" she called into the dark.",
    "\"Run,\" he said. \"Run and do not look back.\"",
    "The captain said nothing for a long moment.",
    "Then the lights came on and everyone laughed.",
    "You found me, she said, and started to cry.",
    "The dog barked once, then the house was silent.",
]

# 8. One word, two words, and twenty words.
LENGTH_EXTREMES = [
    "Hello",
    "Goodbye",
    "Silence",
    "Later",
    "Anyway",
    "Winter",
    "Sorry",
    "Nothing",
    "Good morning",
    "Well done",
    "Come here",
    "Not again",
    "Almost there",
    "Try harder",
    "Nearly finished",
    "Look outside",
    "So cold",
    "Nobody moved",
    "He had been walking for six hours and the road ahead still looked exactly like the road behind him.",
    "She told me once that the hardest part of leaving a place is not the leaving but the arriving somewhere else.",
    "If you follow the river north for about an hour you will come to a wooden bridge and a very old house.",
    "The letter had been in the drawer for eleven years and nobody in the family had ever thought to open it.",
    "Every summer we drove to the same beach and every summer my father said this would be the last time.",
    "I do not know why I kept the ticket but it is still in the pocket of my winter coat.",
    "The doctor said there was nothing to worry about and then asked her to come back again the following week.",
    "There was a moment when everything could still have been different but none of us noticed it at the time.",
]

# 9. Notes to self and forgotten comments.
NOTES_TO_SELF = [
    "note to self: buy milk",
    "TODO: finish this later",
    "fix this properly tomorrow",
    "this part is not finished yet",
    "remember why this was written",
    "ask Mum about the recipe",
    "the old version is in the other folder",
    "this used to work last week",
    "leave this alone for now",
    "check with Tom before deleting",
    "temporary, will tidy up later",
    "borrowed this idea from a book",
    "not sure this is the right approach",
    "I think this is where it went wrong",
    "come back to this after lunch",
]

PROSE = (COMMAND_FIRST_WORD + NUMBERS_AND_UNITS + FUNCTION_WORDS
         + QUESTIONS_AND_COMMANDS + APOSTROPHES + PUNCTUATION
         + STORY_LINES + LENGTH_EXTREMES + NOTES_TO_SELF)

GROUPS = [
    ("command-first-word", COMMAND_FIRST_WORD),
    ("numbers-and-units", NUMBERS_AND_UNITS),
    ("function-words", FUNCTION_WORDS),
    ("questions-and-commands", QUESTIONS_AND_COMMANDS),
    ("apostrophes", APOSTROPHES),
    ("punctuation", PUNCTUATION),
    ("story-lines", STORY_LINES),
    ("length-extremes", LENGTH_EXTREMES),
    ("notes-to-self", NOTES_TO_SELF),
]

if __name__ == "__main__":
    assert len(PROSE) == len(set(PROSE)), "duplicate sentence in the corpus"
    print(len(PROSE), "sentences")
    for name, g in GROUPS:
        print("  %-24s %3d" % (name, len(g)))
