# -*- coding: utf-8 -*-
"""Probe corpus for NME beginner-mistake tolerance measurement.

Each probe: (id, family, lang, source, intent, expect_regex)
  expect_regex is searched (re.M|re.I) against the generated Python.
  None  -> no semantic expectation (verdict only).
"""

# canonical expectations
P_HELLO = r'^print\("hello"\)$'
P_ANNYEONG = r'^print\("안녕"\)$'
SLEEP2 = r'sleep\(2\)'
SLEEP3 = r'sleep\(3\)'
SLEEP1 = r'sleep\(1\)'
RANGE3 = r'range\(3\)'
RANGE1 = r'range\(1\)'
SCORE0 = r'^score = 0$'
JUMSU0 = r'^점수 = 0$'
SCOREADD = r'score = score \+ 1'
JUMSUADD = r'점수 = 점수 \+ 1'
ASKNAME = r'name = input\('
ASKIREUM = r'이름 = input\('
BREAKP = r'^\s+break$'
CONTP = r'^\s+continue$'
IFSCORE = r'if \(score > 10\)'
IFJUMSU = r'if \(점수 > 10\)'
APPEND_EN = r'friends\.append\("Mina"\)'
APPEND_KO = r'친구들\.append\("민수"\)'

# prefixes used so a variable exists
SET_EN = "set score to 0\n"
SET_KO = "점수는 0\n"
LIST_EN = "set friends to list of Mina\n"
LIST_KO = "친구들은 목록 민수\n"

PROBES = []


def P(pid, family, lang, src, intent, expect=None):
    PROBES.append(dict(id=pid, family=family, lang=lang, src=src,
                       intent=intent, expect=expect))


# ---------------------------------------------------------------- 0. controls
# documented-correct forms, used as the baseline and for en/ko asymmetry pairs
P("c-en-say", "control", "en", "say hello", "print hello", P_HELLO)
P("c-en-show", "control", "en", "show hello", "print hello", P_HELLO)
P("c-en-display", "control", "en", "display hello", "print hello", P_HELLO)
P("c-en-tell", "control", "en", "tell hello", "print hello", P_HELLO)
P("c-en-sayrev", "control", "en", "hello show", "print hello", P_HELLO)
P("c-en-wait", "control", "en", "wait 2 seconds", "sleep 2", SLEEP2)
P("c-en-pause", "control", "en", "pause 2", "sleep 2", SLEEP2)
P("c-en-sleep", "control", "en", "sleep 2", "sleep 2", SLEEP2)
P("c-en-waitfor", "control", "en", "wait for 2 seconds", "sleep 2", SLEEP2)
P("c-en-repeat", "control", "en", "repeat 3 times and show hello", "loop 3", RANGE3)
P("c-en-times", "control", "en", "3 times hello", "loop 3 print", RANGE3)
P("c-en-set", "control", "en", "set score to 0", "score=0", SCORE0)
P("c-en-save", "control", "en", "save score to 0", "score=0", SCORE0)
P("c-en-add", "control", "en", SET_EN + "add 1 to score", "score+=1", SCOREADD)
P("c-en-add2", "control", "en", SET_EN + "score add 1", "score+=1", SCOREADD)
P("c-en-ask", "control", "en", "ask name What is your name?", "name=input", ASKNAME)
P("c-en-if", "control", "en", SET_EN + "if score is greater than 10 then show won", "if >10", IFSCORE)
P("c-en-append", "control", "en", LIST_EN + "append Mina to friends", "append", APPEND_EN)
P("c-ko-say", "control", "ko", "말해줘 안녕", "print 안녕", P_ANNYEONG)
P("c-ko-sayrev", "control", "ko", "안녕 말해줘", "print 안녕", P_ANNYEONG)
P("c-ko-boyeojwo", "control", "ko", "보여줘 안녕", "print 안녕", P_ANNYEONG)
P("c-ko-chullyeok", "control", "ko", "출력해 안녕", "print 안녕", P_ANNYEONG)
P("c-ko-wait", "control", "ko", "2초 기다려", "sleep 2", SLEEP2)
P("c-ko-waitjwo", "control", "ko", "2초 기다려줘", "sleep 2", SLEEP2)
P("c-ko-swieo", "control", "ko", "2초 쉬어", "sleep 2", SLEEP2)
P("c-ko-repeat", "control", "ko", "3번 반복해서 안녕 말해줘", "loop 3", RANGE3)
P("c-ko-times", "control", "ko", "3번 안녕", "loop 3 print", RANGE3)
P("c-ko-set", "control", "ko", "점수는 0", "점수=0", JUMSU0)
P("c-ko-save", "control", "ko", "점수 저장 0", "점수=0", JUMSU0)
P("c-ko-add", "control", "ko", SET_KO + "점수에 1 더해", "점수+=1", JUMSUADD)
P("c-ko-ask", "control", "ko", "이름을 물어봐 이름이 뭐예요?", "이름=input", ASKIREUM)
P("c-ko-if", "control", "ko", SET_KO + "만약에 점수가 10보다 크면 성공 말해줘", "if >10", IFJUMSU)
P("c-ko-append", "control", "ko", LIST_KO + "친구들에 민수 넣어", "append", APPEND_KO)

# ------------------------------------------------------- 1. spelling typos EN
P("t-en-01", "typo", "en", "sya hello", "print hello", P_HELLO)
P("t-en-02", "typo", "en", "shwo hello", "print hello", P_HELLO)
P("t-en-03", "typo", "en", "sho hello", "print hello", P_HELLO)
P("t-en-04", "typo", "en", "shoe hello", "print hello", P_HELLO)
P("t-en-05", "typo", "en", "sayy hello", "print hello", P_HELLO)
P("t-en-06", "typo", "en", "saay hello", "print hello", P_HELLO)
P("t-en-07", "typo", "en", "sy hello", "print hello", P_HELLO)
P("t-en-08", "typo", "en", "dispaly hello", "print hello", P_HELLO)
P("t-en-09", "typo", "en", "displya hello", "print hello", P_HELLO)
P("t-en-10", "typo", "en", "tel hello", "print hello", P_HELLO)
P("t-en-11", "typo", "en", "pirnt hello", "print hello", P_HELLO)
P("t-en-12", "typo", "en", "prnt hello", "print hello", P_HELLO)
P("t-en-13", "typo", "en", "waite 2 seconds", "sleep 2", SLEEP2)
P("t-en-14", "typo", "en", "wat 2 seconds", "sleep 2", SLEEP2)
P("t-en-15", "typo", "en", "wiat 2 seconds", "sleep 2", SLEEP2)
P("t-en-16", "typo", "en", "waitt 2 seconds", "sleep 2", SLEEP2)
P("t-en-17", "typo", "en", "wait 2 secnods", "sleep 2", SLEEP2)
P("t-en-18", "typo", "en", "wait 2 second s", "sleep 2", SLEEP2)
P("t-en-19", "typo", "en", "pasue 2", "sleep 2", SLEEP2)
P("t-en-20", "typo", "en", "slep 2", "sleep 2", SLEEP2)
P("t-en-21", "typo", "en", "sleeep 2", "sleep 2", SLEEP2)
P("t-en-22", "typo", "en", "reepat 3 times and show hello", "loop 3", RANGE3)
P("t-en-23", "typo", "en", "repaet 3 times and show hello", "loop 3", RANGE3)
P("t-en-24", "typo", "en", "repet 3 times and show hello", "loop 3", RANGE3)
P("t-en-25", "typo", "en", "repat 3 times and show hello", "loop 3", RANGE3)
P("t-en-26", "typo", "en", "repeat 3 tiems and show hello", "loop 3", RANGE3)
P("t-en-27", "typo", "en", "repeatt 3 times and show hello", "loop 3", RANGE3)
P("t-en-28", "typo", "en", "st score to 0", "score=0", SCORE0)
P("t-en-29", "typo", "en", "sett score to 0", "score=0", SCORE0)
P("t-en-30", "typo", "en", "ste score to 0", "score=0", SCORE0)
P("t-en-31", "typo", "en", "set score t 0", "score=0", SCORE0)
P("t-en-32", "typo", "en", "set score too 0", "score=0", SCORE0)
P("t-en-33", "typo", "en", "sav score to 0", "score=0", SCORE0)
P("t-en-34", "typo", "en", "svae score to 0", "score=0", SCORE0)
P("t-en-35", "typo", "en", "sak name What is your name?", "name=input", ASKNAME)
P("t-en-36", "typo", "en", "aks name What is your name?", "name=input", ASKNAME)
P("t-en-37", "typo", "en", "askk name What is your name?", "name=input", ASKNAME)
P("t-en-38", "typo", "en", "as name What is your name?", "name=input", ASKNAME)
P("t-en-39", "typo", "en", SET_EN + "ad 1 to score", "score+=1", SCOREADD)
P("t-en-40", "typo", "en", SET_EN + "addd 1 to score", "score+=1", SCOREADD)
P("t-en-41", "typo", "en", SET_EN + "add 1 too score", "score+=1", SCOREADD)
P("t-en-42", "typo", "en", SET_EN + "increse score by 1", "score+=1", SCOREADD)
P("t-en-43", "typo", "en", SET_EN + "if score is greatr than 10 then show won", "if >10", IFSCORE)
P("t-en-44", "typo", "en", SET_EN + "if score is grater than 10 then show won", "if >10", IFSCORE)
P("t-en-45", "typo", "en", SET_EN + "iff score is greater than 10 then show won", "if >10", IFSCORE)
P("t-en-46", "typo", "en", SET_EN + "if score is greater then 10 then show won", "if >10", IFSCORE)
P("t-en-47", "typo", "en", "repeat 3 times\n  show hello\nedn", "loop 3 then end", RANGE3)
P("t-en-48", "typo", "en", "repeat 3 times\n  brek\nend", "break in loop", BREAKP)
P("t-en-49", "typo", "en", "repeat 3 times\n  braek\nend", "break in loop", BREAKP)
P("t-en-50", "typo", "en", "repeat 3 times\n  skipp\nend", "continue in loop", CONTP)
P("t-en-51", "typo", "en", "repeat 3 times\n  skp\nend", "continue in loop", CONTP)
P("t-en-52", "typo", "en", LIST_EN + "appned Mina to friends", "append", APPEND_EN)
P("t-en-53", "typo", "en", LIST_EN + "apend Mina to friends", "append", APPEND_EN)
P("t-en-54", "typo", "en", "for eahc friend in friends\n  show friend\nend", "for each", r'for friend in friends')
P("t-en-55", "typo", "en", "for each friend in freinds\n  show friend\nend", "for each (typo var)", r'for friend in freinds')

# ------------------------------------------------------- 1. spelling typos KO
P("t-ko-01", "typo", "ko", "말헤줘 안녕", "print 안녕", P_ANNYEONG)
P("t-ko-02", "typo", "ko", "말해조 안녕", "print 안녕", P_ANNYEONG)
P("t-ko-03", "typo", "ko", "마해줘 안녕", "print 안녕", P_ANNYEONG)
P("t-ko-04", "typo", "ko", "말해쥐 안녕", "print 안녕", P_ANNYEONG)
P("t-ko-05", "typo", "ko", "말해주 안녕", "print 안녕", P_ANNYEONG)
P("t-ko-06", "typo", "ko", "안녕 말헤줘", "print 안녕", P_ANNYEONG)
P("t-ko-07", "typo", "ko", "보여저 안녕", "print 안녕", P_ANNYEONG)
P("t-ko-08", "typo", "ko", "보여좀 안녕", "print 안녕", P_ANNYEONG)
P("t-ko-09", "typo", "ko", "출력헤 안녕", "print 안녕", P_ANNYEONG)
P("t-ko-10", "typo", "ko", "출역해 안녕", "print 안녕", P_ANNYEONG)
P("t-ko-11", "typo", "ko", "2초 기다러", "sleep 2", SLEEP2)
P("t-ko-12", "typo", "ko", "2초 기달려", "sleep 2", SLEEP2)
P("t-ko-13", "typo", "ko", "2초 기디려", "sleep 2", SLEEP2)
P("t-ko-14", "typo", "ko", "2초 기다려어", "sleep 2", SLEEP2)
P("t-ko-15", "typo", "ko", "2초 다려", "sleep 2", SLEEP2)
P("t-ko-16", "typo", "ko", "2초 쉬여", "sleep 2", SLEEP2)
P("t-ko-17", "typo", "ko", "3번 반복헤서 안녕 말해줘", "loop 3", RANGE3)
P("t-ko-18", "typo", "ko", "3번 반보해서 안녕 말해줘", "loop 3", RANGE3)
P("t-ko-19", "typo", "ko", "3번 반복햬서 안녕 말해줘", "loop 3", RANGE3)
P("t-ko-20", "typo", "ko", "3번 밥복해서 안녕 말해줘", "loop 3", RANGE3)
P("t-ko-21", "typo", "ko", "3번 반복해\n  안녕 말해줘\n끝", "loop 3 block", RANGE3)
P("t-ko-22", "typo", "ko", "3번 반복헤\n  안녕 말해줘\n끝", "loop 3 block", RANGE3)
P("t-ko-23", "typo", "ko", "점수 저자해 0", "점수=0", JUMSU0)
P("t-ko-24", "typo", "ko", "점수 저장헤 0", "점수=0", JUMSU0)
P("t-ko-25", "typo", "ko", "점수 기어해 0", "점수=0", JUMSU0)
P("t-ko-26", "typo", "ko", "이름을 무러봐 이름이 뭐예요?", "이름=input", ASKIREUM)
P("t-ko-27", "typo", "ko", "이름을 물어바 이름이 뭐예요?", "이름=input", ASKIREUM)
P("t-ko-28", "typo", "ko", "이름을 물어봐아 이름이 뭐예요?", "이름=input", ASKIREUM)
P("t-ko-29", "typo", "ko", "이름을 질분해 이름이 뭐예요?", "이름=input", ASKIREUM)
P("t-ko-30", "typo", "ko", SET_KO + "점수에 1 더헤", "점수+=1", JUMSUADD)
P("t-ko-31", "typo", "ko", SET_KO + "점수에 1 대해", "점수+=1", JUMSUADD)
P("t-ko-32", "typo", "ko", SET_KO + "점수에 1 더해에", "점수+=1", JUMSUADD)
P("t-ko-33", "typo", "ko", SET_KO + "점수 1 올료", "점수+=1", JUMSUADD)
P("t-ko-34", "typo", "ko", "3번 반복해\n  안녕 말해줘\n끋", "loop 3 block end", RANGE3)
P("t-ko-35", "typo", "ko", "3번 반복해\n  안녕 말해줘\n끗", "loop 3 block end", RANGE3)
P("t-ko-36", "typo", "ko", "3번 반복해\n  멈처\n끝", "break in loop", BREAKP)
P("t-ko-37", "typo", "ko", "3번 반복해\n  머춰\n끝", "break in loop", BREAKP)
P("t-ko-38", "typo", "ko", "3번 반복해\n  건너뛰여\n끝", "continue in loop", CONTP)
P("t-ko-39", "typo", "ko", "3번 반복해\n  건너띄어\n끝", "continue in loop", CONTP)
P("t-ko-40", "typo", "ko", LIST_KO + "친구들에 민수 너어", "append", APPEND_KO)
P("t-ko-41", "typo", "ko", LIST_KO + "친구들에 민수 추가헤", "append", APPEND_KO)
P("t-ko-42", "typo", "ko", SET_KO + "만약게 점수가 10보다 크면 성공 말해줘", "if >10", IFJUMSU)
P("t-ko-43", "typo", "ko", SET_KO + "만얗에 점수가 10보다 크면 성공 말해줘", "if >10", IFJUMSU)
P("t-ko-44", "typo", "ko", SET_KO + "만약에 점수가 10보다 그면 성공 말해줘", "if >10", IFJUMSU)

# ------------------------------------------------------------ 2. word order
P("o-en-01", "order", "en", "hello say", "print hello", P_HELLO)
P("o-en-02", "order", "en", "hello show", "print hello", P_HELLO)
P("o-en-03", "order", "en", "hello display", "print hello", P_HELLO)
P("o-en-04", "order", "en", "3 times repeat and show hello", "loop 3", RANGE3)
P("o-en-05", "order", "en", "times 3 repeat and show hello", "loop 3", RANGE3)
P("o-en-06", "order", "en", "2 seconds wait", "sleep 2", SLEEP2)
P("o-en-07", "order", "en", "seconds 2 wait", "sleep 2", SLEEP2)
P("o-en-08", "order", "en", "2 wait", "sleep 2", SLEEP2)
P("o-en-09", "order", "en", SET_EN + "to score add 1", "score+=1", SCOREADD)
P("o-en-10", "order", "en", SET_EN + "1 add to score", "score+=1", SCOREADD)
P("o-en-11", "order", "en", SET_EN + "add to score 1", "score+=1", SCOREADD)
P("o-en-12", "order", "en", SET_EN + "by 1 increase score", "score+=1", SCOREADD)
P("o-en-13", "order", "en", SET_EN + "score by 2 multiply", "score*=2", r'score = score \* 2')
P("o-en-14", "order", "en", "score set to 0", "score=0", SCORE0)
P("o-en-15", "order", "en", "to 0 set score", "score=0", SCORE0)
P("o-en-16", "order", "en", "0 to score set", "score=0", SCORE0)
P("o-en-17", "order", "en", "name ask", "name=input()", ASKNAME)
P("o-en-18", "order", "en", "ask What is your name? name", "name=input", ASKNAME)
P("o-en-19", "order", "en", SET_EN + "then show won if score is greater than 10", "if >10", IFSCORE)
P("o-en-20", "order", "en", LIST_EN + "to friends append Mina", "append", APPEND_EN)
P("o-ko-01", "order", "ko", "말해줘 안녕", "print 안녕", P_ANNYEONG)
P("o-ko-02", "order", "ko", "반복해 3번 안녕 말해줘", "loop 3", RANGE3)
P("o-ko-03", "order", "ko", "기다려 2초", "sleep 2", SLEEP2)
P("o-ko-04", "order", "ko", "2 기다려", "sleep 2", SLEEP2)
P("o-ko-05", "order", "ko", SET_KO + "1을 점수에 더해", "점수+=1", JUMSUADD)
P("o-ko-06", "order", "ko", SET_KO + "더해 점수에 1", "점수+=1", JUMSUADD)
P("o-ko-07", "order", "ko", SET_KO + "1 더해 점수에", "점수+=1", JUMSUADD)
P("o-ko-08", "order", "ko", "0 점수에 저장해", "점수=0", JUMSU0)
P("o-ko-09", "order", "ko", "저장해 점수 0", "점수=0", JUMSU0)
P("o-ko-10", "order", "ko", "물어봐 이름을 이름이 뭐예요?", "이름=input", ASKIREUM)
P("o-ko-11", "order", "ko", SET_KO + "성공 말해줘 만약에 점수가 10보다 크면", "if >10", IFJUMSU)
P("o-ko-12", "order", "ko", LIST_KO + "민수를 친구들에 넣어", "append", APPEND_KO)
P("o-ko-13", "order", "ko", LIST_KO + "넣어 친구들에 민수", "append", APPEND_KO)

# --------------------------------------------------------------- 3. spacing
P("s-en-01", "spacing", "en", "say  hello", "print hello", P_HELLO)
P("s-en-02", "spacing", "en", "say hello ", "print hello", r'print\("hello"\)')
P("s-en-03", "spacing", "en", "  say hello", "print hello", P_HELLO)
P("s-en-04", "spacing", "en", "sayhello", "print hello", P_HELLO)
P("s-en-05", "spacing", "en", "showhello", "print hello", P_HELLO)
P("s-en-06", "spacing", "en", "wait3 seconds", "sleep 3", SLEEP3)
P("s-en-07", "spacing", "en", "wait 3seconds", "sleep 3", SLEEP3)
P("s-en-08", "spacing", "en", "wait  3  seconds", "sleep 3", SLEEP3)
P("s-en-09", "spacing", "en", "repeat3 times and show hello", "loop 3", RANGE3)
P("s-en-10", "spacing", "en", "repeat 3times and show hello", "loop 3", RANGE3)
P("s-en-11", "spacing", "en", "set  score  to  0", "score=0", SCORE0)
P("s-en-12", "spacing", "en", "setscore to 0", "score=0", SCORE0)
P("s-en-13", "spacing", "en", SET_EN + "add 1to score", "score+=1", SCOREADD)
P("s-en-14", "spacing", "en", "for eachfriend in friends\n  show friend\nend", "for each", r'for friend in friends')
P("s-ko-01", "spacing", "ko", "말해 줘 안녕", "print 안녕", P_ANNYEONG)
P("s-ko-02", "spacing", "ko", "안녕 말해 줘", "print 안녕", P_ANNYEONG)
P("s-ko-03", "spacing", "ko", "보여 줘 안녕", "print 안녕", P_ANNYEONG)
P("s-ko-04", "spacing", "ko", "출력 해 안녕", "print 안녕", P_ANNYEONG)
P("s-ko-05", "spacing", "ko", "말해주세요 안녕", "print 안녕", P_ANNYEONG)
P("s-ko-06", "spacing", "ko", "말해 주세요 안녕", "print 안녕", P_ANNYEONG)
P("s-ko-07", "spacing", "ko", "안녕말해줘", "print 안녕", P_ANNYEONG)
P("s-ko-08", "spacing", "ko", "3번 반복 해서 안녕 말해줘", "loop 3", RANGE3)
P("s-ko-09", "spacing", "ko", "3번반복해서 안녕 말해줘", "loop 3", RANGE3)
P("s-ko-10", "spacing", "ko", "3 번 반복해서 안녕 말해줘", "loop 3", RANGE3)
P("s-ko-11", "spacing", "ko", "2초기다려", "sleep 2", SLEEP2)
P("s-ko-12", "spacing", "ko", "2 초 기다려", "sleep 2", SLEEP2)
P("s-ko-13", "spacing", "ko", "2초 기다 려", "sleep 2", SLEEP2)
P("s-ko-14", "spacing", "ko", "2초 기다려 줘", "sleep 2", SLEEP2)
P("s-ko-15", "spacing", "ko", SET_KO + "점수에1더해", "점수+=1", JUMSUADD)
P("s-ko-16", "spacing", "ko", SET_KO + "점수에 1더해", "점수+=1", JUMSUADD)
P("s-ko-17", "spacing", "ko", "3번 반복해\n  건너 뛰어\n끝", "continue", CONTP)
P("s-ko-18", "spacing", "ko", "3번 반복해\n  여기서 멈춰\n끝", "break", BREAKP)
P("s-ko-19", "spacing", "ko", "3번 반복해\n  여기서멈춰\n끝", "break", BREAKP)
P("s-ko-20", "spacing", "ko", "점수는0", "점수=0", JUMSU0)
P("s-ko-21", "spacing", "ko", "점수 는 0", "점수=0", JUMSU0)
P("s-ko-22", "spacing", "ko", LIST_KO + "친구들에 민수 추가 해", "append", APPEND_KO)

# ------------------------------------------------------------ 4. punctuation
P("p-en-01", "punct", "en", "say hello.", "print hello", r'print\("hello\.?"\)')
P("p-en-02", "punct", "en", "wait 2 seconds.", "sleep 2", SLEEP2)
P("p-en-03", "punct", "en", "wait 2 seconds!", "sleep 2", SLEEP2)
P("p-en-04", "punct", "en", "repeat 3 times and show hello.", "loop 3", RANGE3)
P("p-en-05", "punct", "en", "repeat 3 times.", "loop 3", RANGE3)
P("p-en-06", "punct", "en", "set score to 0.", "score=0", SCORE0)
P("p-en-07", "punct", "en", "set score to 0;", "score=0", SCORE0)
P("p-en-08", "punct", "en", "say: hello", "print hello", P_HELLO)
P("p-en-09", "punct", "en", "show: hello", "print hello", P_HELLO)
P("p-en-10", "punct", "en", "say “hello”", "print hello", P_HELLO)
P("p-en-11", "punct", "en", "say ‘hello’", "print hello", P_HELLO)
P("p-en-12", "punct", "en", 'say "hello",', "print hello", r'print\("hello"')
P("p-en-13", "punct", "en", "set friends to list of Mina, Ada,", "list", r'friends = \["Mina", "Ada"\]')
P("p-en-14", "punct", "en", 'ask name, What is your name?', "name=input", ASKNAME)
P("p-en-15", "punct", "en", "3 times: say hello", "loop 3 one line", RANGE3)
P("p-en-16", "punct", "en", "3 times say hello", "loop 3 one line", RANGE3)
P("p-en-17", "punct", "en", SET_EN + "if score is greater than 10 then show won.", "if", IFSCORE)
P("p-en-18", "punct", "en", SET_EN + "if score is greater than 10: show won", "if", IFSCORE)
P("p-en-19", "punct", "en", SET_EN + "if score > 10 then show won", "if", IFSCORE)
P("p-en-20", "punct", "en", "say hello!!!", "print hello!!!", r'print\("hello!!!"\)')
P("p-en-21", "punct", "en", "wait 2 seconds?", "sleep 2", SLEEP2)
P("p-ko-01", "punct", "ko", "안녕 말해줘.", "print 안녕", r'print\("안녕\.?"\)')
P("p-ko-02", "punct", "ko", "2초 기다려.", "sleep 2", SLEEP2)
P("p-ko-03", "punct", "ko", "2초 기다려!", "sleep 2", SLEEP2)
P("p-ko-04", "punct", "ko", "2초 기다려？", "sleep 2 (fullwidth ?)", SLEEP2)
P("p-ko-05", "punct", "ko", "안녕 말해줘！", "print 안녕 (fullwidth !)", r'print\("안녕')
P("p-ko-06", "punct", "ko", "안녕 말해줘、", "print (ideographic comma)", r'print\("안녕')
P("p-ko-07", "punct", "ko", "3번 반복해서 안녕 말해줘.", "loop 3", RANGE3)
P("p-ko-08", "punct", "ko", "3번 반복해:", "loop 3 block", RANGE3)
P("p-ko-09", "punct", "ko", "점수는 0.", "점수=0", JUMSU0)
P("p-ko-10", "punct", "ko", "점수는 0;", "점수=0", JUMSU0)
P("p-ko-11", "punct", "ko", "말해줘: 안녕", "print 안녕", P_ANNYEONG)
P("p-ko-12", "punct", "ko", "“안녕” 말해", "print 안녕", P_ANNYEONG)
P("p-ko-13", "punct", "ko", "친구들은 목록 민수, 지안,", "list", r'친구들 = \["민수", "지안"\]')
P("p-ko-14", "punct", "ko", "친구들은 목록 민수、지안", "list (ideographic comma)", r'친구들 = \["민수", "지안"\]')
P("p-ko-15", "punct", "ko", "3번: 안녕 말해줘", "loop 3 one line", RANGE3)
P("p-ko-16", "punct", "ko", SET_KO + "만약에 점수가 10보다 크면: 성공 말해줘", "if", IFJUMSU)
P("p-ko-17", "punct", "ko", SET_KO + "만약에 점수 > 10 이면 성공 말해줘", "if", IFJUMSU)
P("p-ko-18", "punct", "ko", "이름을 물어봐, 이름이 뭐예요?", "이름=input", ASKIREUM)

# ------------------------------------------------- 5. particle/ending (ko)
P("k-ko-01", "particle", "ko", "점수는 0", "점수=0", JUMSU0)
P("k-ko-02", "particle", "ko", "점수를 0으로", "점수=0", JUMSU0)
P("k-ko-03", "particle", "ko", "점수 = 0", "점수=0", JUMSU0)
P("k-ko-04", "particle", "ko", "점수가 0", "점수=0", JUMSU0)
P("k-ko-05", "particle", "ko", "점수는 0이다", "점수=0", JUMSU0)
P("k-ko-06", "particle", "ko", "점수는 0입니다", "점수=0", JUMSU0)
P("k-ko-07", "particle", "ko", "점수에 0 저장해", "점수=0", JUMSU0)
P("k-ko-08", "particle", "ko", "점수를 0으로 설정해", "점수=0", JUMSU0)
P("k-ko-09", "particle", "ko", "점수를 0으로 저장해줘", "점수=0", JUMSU0)
P("k-ko-10", "particle", "ko", "말해 안녕", "print 안녕", P_ANNYEONG)
P("k-ko-11", "particle", "ko", "말하기 안녕", "print 안녕", P_ANNYEONG)
P("k-ko-12", "particle", "ko", "말해라 안녕", "print 안녕", P_ANNYEONG)
P("k-ko-13", "particle", "ko", "말합니다 안녕", "print 안녕", P_ANNYEONG)
P("k-ko-14", "particle", "ko", "출력하기 안녕", "print 안녕", P_ANNYEONG)
P("k-ko-15", "particle", "ko", "출력해줘 안녕", "print 안녕", P_ANNYEONG)
P("k-ko-16", "particle", "ko", "출력 안녕", "print 안녕", P_ANNYEONG)
P("k-ko-17", "particle", "ko", "2초 기다려", "sleep 2", SLEEP2)
P("k-ko-18", "particle", "ko", "2초 기다려주세요", "sleep 2", SLEEP2)
P("k-ko-19", "particle", "ko", "2초 대기해", "sleep 2", SLEEP2)
P("k-ko-20", "particle", "ko", "2초 대기", "sleep 2", SLEEP2)
P("k-ko-21", "particle", "ko", "2초 기다립니다", "sleep 2", SLEEP2)
P("k-ko-22", "particle", "ko", "2초 쉬세요", "sleep 2", SLEEP2)
P("k-ko-23", "particle", "ko", "이름 물어봐", "이름=input", ASKIREUM)
P("k-ko-24", "particle", "ko", "이름을 물어봐줘 이름이 뭐예요?", "이름=input", ASKIREUM)
P("k-ko-25", "particle", "ko", "이름을 질문해 이름이 뭐예요?", "이름=input", ASKIREUM)
P("k-ko-26", "particle", "ko", "이름을 입력받아 이름이 뭐예요?", "이름=input", ASKIREUM)
P("k-ko-27", "particle", "ko", "이름을 입력해 이름이 뭐예요?", "이름=input", ASKIREUM)
P("k-ko-28", "particle", "ko", SET_KO + "점수에 1을 더해", "점수+=1", JUMSUADD)
P("k-ko-29", "particle", "ko", SET_KO + "점수에다 1 더해", "점수+=1", JUMSUADD)
P("k-ko-30", "particle", "ko", SET_KO + "점수한테 1 더해", "점수+=1", JUMSUADD)
P("k-ko-31", "particle", "ko", SET_KO + "점수 1 더해", "점수+=1", JUMSUADD)
P("k-ko-32", "particle", "ko", "3번 반복하기\n  안녕 말해줘\n끝", "loop 3", RANGE3)
P("k-ko-33", "particle", "ko", "3번 반복합니다\n  안녕 말해줘\n끝", "loop 3", RANGE3)
P("k-ko-34", "particle", "ko", LIST_KO + "친구들에 민수를 넣어줘", "append", APPEND_KO)
P("k-ko-35", "particle", "ko", LIST_KO + "친구들에다 민수 넣어", "append", APPEND_KO)

# ---------------------------------------------------- 6. plural / number words
P("n-en-01", "number", "en", "wait 1 seconds", "sleep 1", SLEEP1)
P("n-en-02", "number", "en", "wait 2 second", "sleep 2", SLEEP2)
P("n-en-03", "number", "en", "wait 1 second", "sleep 1", SLEEP1)
P("n-en-04", "number", "en", "wait for 2 second", "sleep 2", SLEEP2)
P("n-en-05", "number", "en", "wait two seconds", "sleep 2", SLEEP2)
P("n-en-06", "number", "en", "wait one second", "sleep 1", SLEEP1)
P("n-en-07", "number", "en", "repeat 1 times and show hello", "loop 1", RANGE1)
P("n-en-08", "number", "en", "repeat 1 time and show hello", "loop 1", RANGE1)
P("n-en-09", "number", "en", "repeat 3 time and show hello", "loop 3", RANGE3)
P("n-en-10", "number", "en", "repeat three times and show hello", "loop 3", RANGE3)
P("n-en-11", "number", "en", "repeat once and show hello", "loop 1", RANGE1)
P("n-en-12", "number", "en", "repeat twice and show hello", "loop 2", r'range\(2\)')
P("n-en-13", "number", "en", "3 time hello", "loop 3", RANGE3)
P("n-en-14", "number", "en", "wait 0.5 seconds", "sleep 0.5", r'sleep\(0\.5\)')
P("n-ko-01", "number", "ko", "1번 반복해서 안녕 말해줘", "loop 1", RANGE1)
P("n-ko-02", "number", "ko", "한 번 반복해서 안녕 말해줘", "loop 1", RANGE1)
P("n-ko-03", "number", "ko", "한번 반복해서 안녕 말해줘", "loop 1", RANGE1)
P("n-ko-04", "number", "ko", "세 번 반복해서 안녕 말해줘", "loop 3", RANGE3)
P("n-ko-05", "number", "ko", "세번 반복해서 안녕 말해줘", "loop 3", RANGE3)
P("n-ko-06", "number", "ko", "두 번 반복해서 안녕 말해줘", "loop 2", r'range\(2\)')
P("n-ko-07", "number", "ko", "삼회 반복해서 안녕 말해줘", "loop 3", RANGE3)
P("n-ko-08", "number", "ko", "3회 반복해서 안녕 말해줘", "loop 3", RANGE3)
P("n-ko-09", "number", "ko", "일초 기다려", "sleep 1", SLEEP1)
P("n-ko-10", "number", "ko", "이초 기다려", "sleep 2", SLEEP2)
P("n-ko-11", "number", "ko", "1초 기다려", "sleep 1", SLEEP1)
P("n-ko-12", "number", "ko", "0.5초 기다려", "sleep 0.5", r'sleep\(0\.5\)')
P("n-ko-13", "number", "ko", "2초간 기다려", "sleep 2", SLEEP2)
P("n-ko-14", "number", "ko", "2초동안 기다려", "sleep 2", SLEEP2)

# ------------------------------------------------------- 7. capitalisation (en)
P("C-en-01", "caps", "en", "Say hello", "print hello", P_HELLO)
P("C-en-02", "caps", "en", "SAY hello", "print hello", P_HELLO)
P("C-en-03", "caps", "en", "Show hello", "print hello", P_HELLO)
P("C-en-04", "caps", "en", "SHOW hello", "print hello", P_HELLO)
P("C-en-05", "caps", "en", "Show Hello World", "print Hello World", r'print\("Hello World"\)')
P("C-en-06", "caps", "en", "Repeat 3 Times and show hello", "loop 3", RANGE3)
P("C-en-07", "caps", "en", "REPEAT 3 TIMES and show hello", "loop 3", RANGE3)
P("C-en-08", "caps", "en", "Wait 2 Seconds", "sleep 2", SLEEP2)
P("C-en-09", "caps", "en", "WAIT 2 SECONDS", "sleep 2", SLEEP2)
P("C-en-10", "caps", "en", "Set score To 0", "score=0", SCORE0)
P("C-en-11", "caps", "en", "SET score TO 0", "score=0", SCORE0)
P("C-en-12", "caps", "en", SET_EN + "Add 1 to score", "score+=1", SCOREADD)
P("C-en-13", "caps", "en", "Ask name What is your name?", "name=input", ASKNAME)
P("C-en-14", "caps", "en", SET_EN + "If score is greater than 10 then show won", "if", IFSCORE)
P("C-en-15", "caps", "en", "repeat 3 times\n  show hello\nEnd", "loop end", RANGE3)
P("C-en-16", "caps", "en", "repeat 3 times\n  Break\nend", "break", BREAKP)
P("C-en-17", "caps", "en", "repeat 3 times\n  Skip\nend", "continue", CONTP)
P("C-en-18", "caps", "en", "Pause 2", "sleep 2", SLEEP2)
P("C-en-19", "caps", "en", LIST_EN + "Append Mina to friends", "append", APPEND_EN)
P("C-en-20", "caps", "en", "For each friend in friends\n  show friend\nend", "for each", r'for friend in friends')

# --------------------------------------------------------- 8. near-miss synonyms
P("y-en-01", "synonym", "en", "output hello", "print hello", P_HELLO)
P("y-en-02", "synonym", "en", "write hello", "print hello", P_HELLO)
P("y-en-03", "synonym", "en", "speak hello", "print hello", P_HELLO)
P("y-en-04", "synonym", "en", "echo hello", "print hello", P_HELLO)
P("y-en-05", "synonym", "en", "puts hello", "print hello", P_HELLO)
P("y-en-06", "synonym", "en", "log hello", "print hello", P_HELLO)
P("y-en-07", "synonym", "en", "loop 3 times and show hello", "loop 3", RANGE3)
P("y-en-08", "synonym", "en", "iterate 3 times and show hello", "loop 3", RANGE3)
P("y-en-09", "synonym", "en", "do 3 times and show hello", "loop 3", RANGE3)
P("y-en-10", "synonym", "en", "again 3 times and show hello", "loop 3", RANGE3)
P("y-en-11", "synonym", "en", "repeat 3 times\n  keep going\nend", "continue", CONTP)
P("y-en-12", "synonym", "en", "repeat 3 times\n  stop here\nend", "break", BREAKP)
P("y-en-13", "synonym", "en", "repeat 3 times\n  exit loop\nend", "break", BREAKP)
P("y-en-14", "synonym", "en", "repeat 3 times\n  next one\nend", "continue", CONTP)
P("y-en-15", "synonym", "en", "repeat 3 times\n  quit\nend", "break", BREAKP)
P("y-en-16", "synonym", "en", "store score as 0", "score=0", SCORE0)
P("y-en-17", "synonym", "en", "let score be 0", "score=0", SCORE0)
P("y-en-18", "synonym", "en", "assign 0 to score", "score=0", SCORE0)
P("y-en-19", "synonym", "en", "make score 0", "score=0", SCORE0)
P("y-en-20", "synonym", "en", "delay 2 seconds", "sleep 2", SLEEP2)
P("y-en-21", "synonym", "en", "hold 2 seconds", "sleep 2", SLEEP2)
P("y-en-22", "synonym", "en", "rest 2 seconds", "sleep 2", SLEEP2)
P("y-en-23", "synonym", "en", "input name What is your name?", "name=input", ASKNAME)
P("y-en-24", "synonym", "en", "read name What is your name?", "name=input", ASKNAME)
P("y-en-25", "synonym", "en", "get name What is your name?", "name=input", ASKNAME)
P("y-en-26", "synonym", "en", LIST_EN + "add Mina to friends", "append", APPEND_EN)
P("y-en-27", "synonym", "en", LIST_EN + "insert Mina into friends", "append", APPEND_EN)
P("y-en-28", "synonym", "en", SET_EN + "raise score by 1", "score+=1", SCOREADD)
P("y-en-29", "synonym", "en", SET_EN + "bump score by 1", "score+=1", SCOREADD)
P("y-en-30", "synonym", "en", "repeat 3 times\n  show hello\nfinish", "loop end", RANGE3)
P("y-en-31", "synonym", "en", "repeat 3 times\n  show hello\ndone", "loop end", RANGE3)
P("y-ko-01", "synonym", "ko", "3번 반복해\n  그만해\n끝", "break", BREAKP)
P("y-ko-02", "synonym", "ko", "3번 반복해\n  멈추기\n끝", "break", BREAKP)
P("y-ko-03", "synonym", "ko", "3번 반복해\n  정지해\n끝", "break", BREAKP)
P("y-ko-04", "synonym", "ko", "3번 반복해\n  종료해\n끝", "break", BREAKP)
P("y-ko-05", "synonym", "ko", "3번 반복해\n  계속해\n끝", "continue", CONTP)
P("y-ko-06", "synonym", "ko", "3번 반복해\n  넘겨\n끝", "continue", CONTP)
P("y-ko-07", "synonym", "ko", "3번 반복해\n  다음\n끝", "continue", CONTP)
P("y-ko-08", "synonym", "ko", "출력하기 안녕", "print 안녕", P_ANNYEONG)
P("y-ko-09", "synonym", "ko", "프린트해 안녕", "print 안녕", P_ANNYEONG)
P("y-ko-10", "synonym", "ko", "적어줘 안녕", "print 안녕", P_ANNYEONG)
P("y-ko-11", "synonym", "ko", "써줘 안녕", "print 안녕", P_ANNYEONG)
P("y-ko-12", "synonym", "ko", "보여주기 안녕", "print 안녕", P_ANNYEONG)
P("y-ko-13", "synonym", "ko", "3번 되풀이해서 안녕 말해줘", "loop 3", RANGE3)
P("y-ko-14", "synonym", "ko", "3번 돌려서 안녕 말해줘", "loop 3", RANGE3)
P("y-ko-15", "synonym", "ko", "3번 루프해서 안녕 말해줘", "loop 3", RANGE3)
P("y-ko-16", "synonym", "ko", "2초 멈춰줘", "sleep 2", SLEEP2)
P("y-ko-17", "synonym", "ko", "2초 잠시멈춰", "sleep 2", SLEEP2)
P("y-ko-18", "synonym", "ko", "2초 슬립", "sleep 2", SLEEP2)
P("y-ko-19", "synonym", "ko", "점수를 0으로 지정해", "점수=0", JUMSU0)
P("y-ko-20", "synonym", "ko", "점수를 0으로 정해", "점수=0", JUMSU0)
P("y-ko-21", "synonym", "ko", "점수를 0으로 만들어", "점수=0", JUMSU0)
P("y-ko-22", "synonym", "ko", "이름을 여쭤봐 이름이 뭐예요?", "이름=input", ASKIREUM)
P("y-ko-23", "synonym", "ko", "이름을 받아 이름이 뭐예요?", "이름=input", ASKIREUM)
P("y-ko-24", "synonym", "ko", LIST_KO + "친구들에 민수 더해", "append", APPEND_KO)
P("y-ko-25", "synonym", "ko", LIST_KO + "친구들에 민수 집어넣어", "append", APPEND_KO)
P("y-ko-26", "synonym", "ko", "3번 반복해\n  안녕 말해줘\n종료", "loop end", RANGE3)
P("y-ko-27", "synonym", "ko", "3번 반복해\n  안녕 말해줘\n마침", "loop end", RANGE3)
P("y-ko-28", "synonym", "ko", SET_KO + "점수를 1 증가해", "점수+=1", JUMSUADD)
P("y-ko-29", "synonym", "ko", SET_KO + "점수를 1 감소해", "점수-=1", r'점수 = 점수 - 1')
